// Copyright (c) 2026 Kata Containers community
//
// SPDX-License-Identifier: Apache-2.0

//! FR-7 — lift the mediation-manifest coverage check to build time.
//!
//! `src/agent/src/mediation.rs` classifies every method of the agent ttRPC service by the
//! enforcement point it must pass through. That table is only a proof of complete
//! mediation if it cannot silently fall out of sync with the service definition, so the
//! coverage check has to fail for *anyone who compiles the agent* — not only for whoever
//! remembers to run the test suite.
//!
//! This script parses the RPC declarations out of `agent.proto` and emits them as a
//! `const PROTO_RPCS: &[(&str, &str)]`. `mediation.rs` then compares that generated table
//! against `MEDIATION_MANIFEST` in a `const` block, so drift is a compile error.
//!
//! Note what is deliberately *not* done here: this script does not parse `mediation.rs`.
//! Proving a property of Rust source by scanning its text is the mistake F-43 recorded —
//! it is cfg-blind, order-blind and dead-code-blind. Only the proto (a small, stable,
//! line-oriented grammar) is parsed; the comparison itself happens in the compiler,
//! against the real symbol, in the real build configuration.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// Path to the agent service definition, relative to this crate's manifest directory.
const AGENT_PROTO: &str = "../libs/protocols/protos/agent.proto";

/// Extract `(method, request type)` for every `rpc <Name>(<Request>)` the proto declares.
///
/// Mirrors the parse in `mediation.rs`: the policy entry point is the protobuf *message*
/// name, so a package-qualified request type is reduced to its bare message name.
fn parse_rpcs(proto: &str) -> Vec<(String, String)> {
    proto
        .lines()
        .filter_map(|line| {
            let rest = line.trim().strip_prefix("rpc ")?;
            let open = rest.find('(')?;
            let close = rest[open..].find(')')? + open;
            let name = rest[..open].trim().to_string();
            let req = rest[open + 1..close]
                .trim()
                .rsplit('.')
                .next()
                .unwrap_or_default()
                .to_string();
            (!name.is_empty() && !req.is_empty()).then_some((name, req))
        })
        .collect()
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", AGENT_PROTO);

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let proto_path = Path::new(&manifest_dir).join(AGENT_PROTO);

    let proto = fs::read_to_string(&proto_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", proto_path.display()));

    let rpcs = parse_rpcs(&proto);
    assert!(
        !rpcs.is_empty(),
        "parsed no rpc declarations from {}; the FR-7 mediation gate would pass vacuously",
        proto_path.display()
    );

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from the agent proto. Do not edit.\n\
         //\n\
         // Every `rpc <Name>(<Request>)` declared by the agent ttRPC service, as\n\
         // `(method, request message)`. Compared against `MEDIATION_MANIFEST` in a `const`\n\
         // block so that an unclassified RPC is a compile error (FR-7).\n\
         pub const PROTO_RPCS: &[(&str, &str)] = &[\n",
    );
    for (method, req) in &rpcs {
        writeln!(out, "    ({:?}, {:?}),", method, req).expect("writing to a String cannot fail");
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let dest = Path::new(&out_dir).join("proto_rpcs.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
