// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
#![allow(clippy::all)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct VmClient {
    client: ::ttrpc::r#async::Client,
}

impl VmClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        VmClient {
            client,
        }
    }

    pub async fn create_vm(&self, ctx: ttrpc::context::Context, req: &super::vmservice::CreateVMRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "CreateVM", cres);
    }

    pub async fn teardown_vm(&self, ctx: ttrpc::context::Context, req: &super::empty::Empty) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "TeardownVM", cres);
    }

    pub async fn pause_vm(&self, ctx: ttrpc::context::Context, req: &super::empty::Empty) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "PauseVM", cres);
    }

    pub async fn resume_vm(&self, ctx: ttrpc::context::Context, req: &super::empty::Empty) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "ResumeVM", cres);
    }

    pub async fn wait_vm(&self, ctx: ttrpc::context::Context, req: &super::empty::Empty) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "WaitVM", cres);
    }

    pub async fn capabilities_vm(&self, ctx: ttrpc::context::Context, req: &super::empty::Empty) -> ::ttrpc::Result<super::vmservice::CapabilitiesVMResponse> {
        let mut cres = super::vmservice::CapabilitiesVMResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "CapabilitiesVM", cres);
    }

    pub async fn properties_vm(&self, ctx: ttrpc::context::Context, req: &super::vmservice::PropertiesVMRequest) -> ::ttrpc::Result<super::vmservice::PropertiesVMResponse> {
        let mut cres = super::vmservice::PropertiesVMResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "PropertiesVM", cres);
    }

    pub async fn modify_resource(&self, ctx: ttrpc::context::Context, req: &super::vmservice::ModifyResourceRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "ModifyResource", cres);
    }

    pub async fn add_pcie_device(&self, ctx: ttrpc::context::Context, req: &super::vmservice::AddPcieDeviceRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "AddPcieDevice", cres);
    }

    pub async fn remove_pcie_device(&self, ctx: ttrpc::context::Context, req: &super::vmservice::RemovePcieDeviceRequest) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "RemovePcieDevice", cres);
    }

    pub async fn quit(&self, ctx: ttrpc::context::Context, req: &super::empty::Empty) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::async_client_request!(self, ctx, req, "vmservice.VM", "Quit", cres);
    }
}

struct CreateVmMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CreateVmMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, vmservice, CreateVMRequest, create_vm);
    }
}

struct TeardownVmMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for TeardownVmMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, empty, Empty, teardown_vm);
    }
}

struct PauseVmMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for PauseVmMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, empty, Empty, pause_vm);
    }
}

struct ResumeVmMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ResumeVmMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, empty, Empty, resume_vm);
    }
}

struct WaitVmMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for WaitVmMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, empty, Empty, wait_vm);
    }
}

struct CapabilitiesVmMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CapabilitiesVmMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, empty, Empty, capabilities_vm);
    }
}

struct PropertiesVmMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for PropertiesVmMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, vmservice, PropertiesVMRequest, properties_vm);
    }
}

struct ModifyResourceMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ModifyResourceMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, vmservice, ModifyResourceRequest, modify_resource);
    }
}

struct AddPcieDeviceMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AddPcieDeviceMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, vmservice, AddPcieDeviceRequest, add_pcie_device);
    }
}

struct RemovePcieDeviceMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for RemovePcieDeviceMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, vmservice, RemovePcieDeviceRequest, remove_pcie_device);
    }
}

struct QuitMethod {
    service: Arc<dyn Vm + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for QuitMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, empty, Empty, quit);
    }
}

#[async_trait]
pub trait Vm: Sync {
    async fn create_vm(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::vmservice::CreateVMRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/CreateVM is not supported".to_string())))
    }
    async fn teardown_vm(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::empty::Empty) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/TeardownVM is not supported".to_string())))
    }
    async fn pause_vm(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::empty::Empty) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/PauseVM is not supported".to_string())))
    }
    async fn resume_vm(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::empty::Empty) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/ResumeVM is not supported".to_string())))
    }
    async fn wait_vm(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::empty::Empty) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/WaitVM is not supported".to_string())))
    }
    async fn capabilities_vm(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::empty::Empty) -> ::ttrpc::Result<super::vmservice::CapabilitiesVMResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/CapabilitiesVM is not supported".to_string())))
    }
    async fn properties_vm(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::vmservice::PropertiesVMRequest) -> ::ttrpc::Result<super::vmservice::PropertiesVMResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/PropertiesVM is not supported".to_string())))
    }
    async fn modify_resource(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::vmservice::ModifyResourceRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/ModifyResource is not supported".to_string())))
    }
    async fn add_pcie_device(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::vmservice::AddPcieDeviceRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/AddPcieDevice is not supported".to_string())))
    }
    async fn remove_pcie_device(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::vmservice::RemovePcieDeviceRequest) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/RemovePcieDevice is not supported".to_string())))
    }
    async fn quit(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::empty::Empty) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/vmservice.Vm/Quit is not supported".to_string())))
    }
}

pub fn create_vm(service: Arc<dyn Vm + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("CreateVM".to_string(),
                    Box::new(CreateVmMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("TeardownVM".to_string(),
                    Box::new(TeardownVmMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("PauseVM".to_string(),
                    Box::new(PauseVmMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ResumeVM".to_string(),
                    Box::new(ResumeVmMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("WaitVM".to_string(),
                    Box::new(WaitVmMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("CapabilitiesVM".to_string(),
                    Box::new(CapabilitiesVmMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("PropertiesVM".to_string(),
                    Box::new(PropertiesVmMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ModifyResource".to_string(),
                    Box::new(ModifyResourceMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("AddPcieDevice".to_string(),
                    Box::new(AddPcieDeviceMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("RemovePcieDevice".to_string(),
                    Box::new(RemovePcieDeviceMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Quit".to_string(),
                    Box::new(QuitMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("vmservice.VM".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
