#!/usr/bin/env bash
#
# Copyright (c) 2026 Microsoft Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# shellcheck source-path=SCRIPTDIR
# 00 — adopt a prebuilt node image (AKS) in place of stages 01-04.
#
# Stages 01-04 provision a VM, bootstrap it, stand up Kubernetes and build the
# guest stack from source. On AKS none of that is ours to do: the cluster and
# the node image already exist. What stages 05+ actually need from 01-04 is not
# the building — it is the *knowledge* of what is installed, which is what lets
# assert_local_guest_installed() refuse to run against the wrong stack.
#
# So this stage does the same job by inspection instead of by construction:
#
#   1. find the node, the RuntimeClass and the install prefix, from the cluster;
#   2. assert the shipped kata-agent really carries the strict-policy build —
#      the one static check that answers "was this image constructed correctly";
#   3. record digests so later stages can prove they still describe that image;
#   4. write coco-env.sh and mark 01-04 done so run-all.sh flows into stage 05.
#
# Usage (from anywhere with kubectl and a cargo toolchain for genpolicy):
#
#   export KUBECONFIG=~/.kube/aks.config
#   export E2E_PLATFORM=aks E2E_STATE_DIR=~/.coco-e2e-aks
#   export E2E_REPO_DIR=~/kata-manifold-cc E2E_BRANCH=manifold-cc
#   ./00-adopt-node.sh && ./05-smoke-test.sh
set -uo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
skip_if_done 00-adopt-node

[[ "${E2E_PLATFORM}" = "aks" ]] \
  || die "00-adopt-node.sh is for E2E_PLATFORM=aks (got: ${E2E_PLATFORM}).
The other platforms build the stack themselves in stage 04."

step "00 — adopt prebuilt node image"
load_toolchain

# The repo is still needed even though nothing is built from it here: genpolicy,
# rules.rego and genpolicy-settings.json all come from the branch, and a policy
# generated by a different vintage than the agent enforcing it is the failure
# mode ensure_branch_genpolicy() exists to prevent.
[[ -d "${E2E_REPO_DIR}" ]] \
  || die "missing ${E2E_REPO_DIR} — clone ${E2E_REPO_URL} (${E2E_BRANCH}) there first"
log "policy inputs will come from ${E2E_REPO_DIR} ($(git -C "${E2E_REPO_DIR}" rev-parse --short HEAD 2>/dev/null || echo unknown))"

step "00a — discover the node under test"
aks_discover
aks_node_pod_up

step "00b — locate the installed payload"
aks_locate_payload
aks_node_exec "ls -l /host${E2E_KATA_DEFAULTS} 2>/dev/null | head -20" || true

# The handler behind the RuntimeClass has to be one containerd actually knows
# about. A RuntimeClass naming a handler containerd never registered does not
# fail at apply time — the pod is admitted and then sits in ContainerCreating,
# which reads as a guest boot problem rather than as a wiring problem.
step "00c — check the RuntimeClass is wired to a real containerd handler"
HANDLER=$(kubectl get runtimeclass "${E2E_RUNTIMECLASS}" -o jsonpath='{.handler}' 2>/dev/null)
[[ -n "${HANDLER}" ]] || die "RuntimeClass ${E2E_RUNTIMECLASS} has no handler"
CTRD_DUMP=$(aks_containerd_config_dump)
[[ -n "${CTRD_DUMP}" ]] || die "could not read containerd's config from ${E2E_NODE}"
aks_require_toml_dump "${CTRD_DUMP}"
grep -q "runtimes\.${HANDLER}\b\|\"${HANDLER}\"" <<<"${CTRD_DUMP}" \
  || die "containerd on ${E2E_NODE} has no runtime handler '${HANDLER}'
RuntimeClass ${E2E_RUNTIMECLASS} points at a handler this node does not implement,
so every pod using it would hang in ContainerCreating."
ok "handler '${HANDLER}' is registered in containerd"

# Being registered is not the same as being the *right* handler. A node can ship
# two complete kata stacks side by side — a legacy one under /usr/share and the
# confidential one under /opt/confidential-containers — each with its own
# ConfigPath, its own guest image and its own annotation allowlist. If the
# RuntimeClass resolves to the legacy handler then every strict-bits assertion
# stage 00d makes is true of an image that never boots, the cc_init_data
# annotation is silently dropped, and stage 05 reports "exec succeeded" with no
# hint that it exercised the wrong stack. Tie the handler back to the payload.
HANDLER_CFG="${E2E_HANDLER_CONFIG:-$(aks_handler_config_path "${HANDLER}" "${CTRD_DUMP}")}"
# No ConfigPath means the shim falls back to a built-in default we would have to
# guess at, and guessing is exactly what this stage exists not to do: the whole
# point of 00c is to prove which of the node's kata stacks the RuntimeClass
# reaches. Refuse rather than continue — a skipped binding check would let 00d
# certify /opt/confidential-containers while pods boot something else entirely.
[[ -n "${HANDLER_CFG}" ]] || die "handler '${HANDLER}' declares no ConfigPath

Without it there is no way to tell which kata stack ${E2E_RUNTIMECLASS} actually
runs, so no assertion this stage makes about ${E2E_KATA_PREFIX} would be about the
image your pods boot. Set E2E_HANDLER_CONFIG to the configuration.toml this
handler resolves to if you know it.

  handlers on this node:
$(aks_handler_table "${CTRD_DUMP}")"

log "handler '${HANDLER}' ConfigPath: ${HANDLER_CFG}"
[[ "${HANDLER_CFG}" = "${E2E_KATA_PREFIX}"/* ]] \
  || die "RuntimeClass ${E2E_RUNTIMECLASS} runs the WRONG kata stack

  handler          ${HANDLER}
  its ConfigPath   ${HANDLER_CFG}
  payload under    ${E2E_KATA_PREFIX}

The confidential payload this image ships lives under ${E2E_KATA_PREFIX}, but the
RuntimeClass resolves to a handler configured against a different tree. Pods using
it boot that other guest image, and because its enable_annotations list has no
'cc_init_data' entry the generated policy is dropped without an error — the pod
comes up and exec is allowed. Point a RuntimeClass at the handler whose ConfigPath
is under ${E2E_KATA_PREFIX} and re-run.

  handlers on this node:
$(aks_handler_table "${CTRD_DUMP}")"
ok "handler '${HANDLER}' runs the payload under ${E2E_KATA_PREFIX}"

# kata's default for enable_annotations is the empty list — every annotation
# denied. So a config with no such line is not "unknown", it is "cc_init_data
# will be dropped", and an unreadable one is not evidence of anything. Both have
# to fail here; treating either as a pass reintroduces the silent-drop failure
# this check exists to catch.
aks_node_exec "test -r /host${HANDLER_CFG}" >/dev/null 2>&1 \
  || die "cannot read ${HANDLER_CFG} on ${E2E_NODE}
It is the config behind handler '${HANDLER}', and without it there is no way to
confirm the cc_init_data annotation is allowed through."
ANN=$(aks_node_exec "grep -h '^[[:space:]]*enable_annotations' /host${HANDLER_CFG} 2>/dev/null" || true)
[[ -n "${ANN}" ]] || die "${HANDLER_CFG} sets no enable_annotations

kata denies every annotation by default, so genpolicy's policy — which is
delivered through the cc_init_data annotation — would be dropped without an
error and every pod would run unmediated."
grep -q 'cc_init_data' <<<"${ANN}" \
  || die "the config behind handler '${HANDLER}' does not allow the cc_init_data annotation
  ${ANN}
genpolicy delivers the policy through that annotation, so the runtime would drop
it silently and every pod would run unmediated."
ok "cc_init_data is in the handler's enable_annotations allowlist"

step "00d — image layers must arrive as host EROFS, not guest-pull"
aks_assert_erofs_layers "${HANDLER}" "${CTRD_DUMP}"

step "00e — are the strict bits actually in the shipped image?"
aks_assert_strict_image

step "00f — record the baseline"
aks_record_baseline

# coco-env.sh is what load_coco_env() reads in every later stage. On the other
# platforms stage 03 writes it; write the AKS equivalent here so stage 05 needs
# no special-casing at all.
ENV_FILE="${HOME}/coco-env.sh"
cat > "${ENV_FILE}" <<EOF
# written by 00-adopt-node.sh — prebuilt AKS node image
export E2E_PLATFORM=aks
export E2E_NODE=${E2E_NODE}
export E2E_RUNTIMECLASS=${E2E_RUNTIMECLASS}
export E2E_KATA_PREFIX=${E2E_KATA_PREFIX}
export KUBECONFIG=${KUBECONFIG:-${HOME}/.kube/config}
# Layers are built and hashed on the node and attached to the guest as verified
# EROFS block devices — 00d proves it rather than assuming it. This is not the
# guest-pull path the confpods platforms deploy, and recording it as such would
# misdescribe every later stage's policy: under guest-pull genpolicy declares no
# layer storages at all.
export PULL_TYPE=host-erofs
EOF
ok "wrote ${ENV_FILE}"

# Stages 01-04 are structurally inapplicable here, not merely skipped: marking
# them done is the honest record, because their *output* — a known, inspected
# guest stack on a known node — is what this stage just produced by other means.
for s in 01-provision-vm 02-bootstrap-node 03-deploy-cluster 04-build-guest-stack; do
  mark_done "${s}"
done
ok "stages 01-04 marked done (superseded by adoption)"

printf '\n'
ok "node        ${E2E_NODE}"
ok "image       ${AKS_NODE_IMAGE_VERSION}"
ok "runtime     ${E2E_RUNTIMECLASS} -> ${HANDLER}"
ok "prefix      ${E2E_KATA_PREFIX}"
log "next: ./05-smoke-test.sh"

mark_done 00-adopt-node
