---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kata-deploy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kata-deploy
  template:
    metadata:
      labels:
        name: kata-deploy
    spec:
      serviceAccountName: kata-deploy-sa
      hostPID: true
      containers:
        - name: kube-kata
          image: ghcr.io/kata-containers/kata-deploy-ci:e94490232e24e4ebb63a97467a586a62e6069d08-nightly-amd64
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["bash", "-c", "/opt/kata-artifacts/scripts/kata-deploy.sh cleanup"]
          command: ["bash", "-c", "/opt/kata-artifacts/scripts/kata-deploy.sh install"]
          # NOTE: Please don't change the order of the environment variables below.
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DEBUG
              value: "true"
            - name: SHIMS
              value: "clh"
            - name: DEFAULT_SHIM
              value: "clh"
            - name: CREATE_RUNTIMECLASSES
              value: "true"
            - name: CREATE_DEFAULT_RUNTIMECLASS
              value: "true"
            - name: ALLOWED_HYPERVISOR_ANNOTATIONS
              value: "default_vcpus"
            - name: SNAPSHOTTER_HANDLER_MAPPING
              value: ""
            - name: AGENT_HTTPS_PROXY
              value: ""
            - name: AGENT_NO_PROXY
              value: ""
            - name: PULL_TYPE_MAPPING
              value: ""
          securityContext:
            privileged: true
          volumeMounts:
            - name: crio-conf
              mountPath: /etc/crio/
            - name: containerd-conf
              mountPath: /etc/containerd/
            - name: kata-artifacts
              mountPath: /opt/kata/
            - name: local-bin
              mountPath: /usr/local/bin/
            - name: host
              mountPath: /host/
      volumes:
        - name: crio-conf
          hostPath:
            path: /etc/crio/
        - name: containerd-conf
          hostPath:
            path: /etc/containerd/
        - name: kata-artifacts
          hostPath:
            path: /opt/kata/
            type: DirectoryOrCreate
        - name: local-bin
          hostPath:
            path: /usr/local/bin/
        - name: host
          hostPath:
            path: /
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
