// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vmservice.proto

package vmservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google/protobuf"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// Modify existing VM request/response
//
type ModifyType int32

const (
	ModifyType_ADD    ModifyType = 0
	ModifyType_REMOVE ModifyType = 1
	ModifyType_UPDATE ModifyType = 2
)

var ModifyType_name = map[int32]string{
	0: "ADD",
	1: "REMOVE",
	2: "UPDATE",
}

var ModifyType_value = map[string]int32{
	"ADD":    0,
	"REMOVE": 1,
	"UPDATE": 2,
}

func (x ModifyType) String() string {
	return proto.EnumName(ModifyType_name, int32(x))
}

func (ModifyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{0}
}

type DiskType int32

const (
	DiskType_SCSI_DISK_TYPE_VHD1     DiskType = 0
	DiskType_SCSI_DISK_TYPE_VHDX     DiskType = 1
	DiskType_SCSI_DISK_TYPE_PHYSICAL DiskType = 2
)

var DiskType_name = map[int32]string{
	0: "SCSI_DISK_TYPE_VHD1",
	1: "SCSI_DISK_TYPE_VHDX",
	2: "SCSI_DISK_TYPE_PHYSICAL",
}

var DiskType_value = map[string]int32{
	"SCSI_DISK_TYPE_VHD1":     0,
	"SCSI_DISK_TYPE_VHDX":     1,
	"SCSI_DISK_TYPE_PHYSICAL": 2,
}

func (x DiskType) String() string {
	return proto.EnumName(DiskType_name, int32(x))
}

func (DiskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{1}
}

type PropertiesVMRequest_PropertiesType int32

const (
	PropertiesVMRequest_Memory    PropertiesVMRequest_PropertiesType = 0
	PropertiesVMRequest_Processor PropertiesVMRequest_PropertiesType = 1
)

var PropertiesVMRequest_PropertiesType_name = map[int32]string{
	0: "Memory",
	1: "Processor",
}

var PropertiesVMRequest_PropertiesType_value = map[string]int32{
	"Memory":    0,
	"Processor": 1,
}

func (x PropertiesVMRequest_PropertiesType) String() string {
	return proto.EnumName(PropertiesVMRequest_PropertiesType_name, int32(x))
}

func (PropertiesVMRequest_PropertiesType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{12, 0}
}

type CapabilitiesVMResponse_Resource int32

const (
	CapabilitiesVMResponse_Vpmem     CapabilitiesVMResponse_Resource = 0
	CapabilitiesVMResponse_Scsi      CapabilitiesVMResponse_Resource = 1
	CapabilitiesVMResponse_Vpci      CapabilitiesVMResponse_Resource = 2
	CapabilitiesVMResponse_Plan9     CapabilitiesVMResponse_Resource = 3
	CapabilitiesVMResponse_VMNic     CapabilitiesVMResponse_Resource = 4
	CapabilitiesVMResponse_Memory    CapabilitiesVMResponse_Resource = 5
	CapabilitiesVMResponse_Processor CapabilitiesVMResponse_Resource = 6
)

var CapabilitiesVMResponse_Resource_name = map[int32]string{
	0: "Vpmem",
	1: "Scsi",
	2: "Vpci",
	3: "Plan9",
	4: "VMNic",
	5: "Memory",
	6: "Processor",
}

var CapabilitiesVMResponse_Resource_value = map[string]int32{
	"Vpmem":     0,
	"Scsi":      1,
	"Vpci":      2,
	"Plan9":     3,
	"VMNic":     4,
	"Memory":    5,
	"Processor": 6,
}

func (x CapabilitiesVMResponse_Resource) String() string {
	return proto.EnumName(CapabilitiesVMResponse_Resource_name, int32(x))
}

func (CapabilitiesVMResponse_Resource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{14, 0}
}

type CapabilitiesVMResponse_SupportedGuestOS int32

const (
	CapabilitiesVMResponse_Windows CapabilitiesVMResponse_SupportedGuestOS = 0
	CapabilitiesVMResponse_Linux   CapabilitiesVMResponse_SupportedGuestOS = 1
)

var CapabilitiesVMResponse_SupportedGuestOS_name = map[int32]string{
	0: "Windows",
	1: "Linux",
}

var CapabilitiesVMResponse_SupportedGuestOS_value = map[string]int32{
	"Windows": 0,
	"Linux":   1,
}

func (x CapabilitiesVMResponse_SupportedGuestOS) String() string {
	return proto.EnumName(CapabilitiesVMResponse_SupportedGuestOS_name, int32(x))
}

func (CapabilitiesVMResponse_SupportedGuestOS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{14, 1}
}

//
// VM lifecycle request/response
//
type DirectBoot struct {
	KernelPath           string   `protobuf:"bytes,1,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	InitrdPath           string   `protobuf:"bytes,2,opt,name=initrd_path,json=initrdPath,proto3" json:"initrd_path,omitempty"`
	KernelCmdline        string   `protobuf:"bytes,3,opt,name=kernel_cmdline,json=kernelCmdline,proto3" json:"kernel_cmdline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectBoot) Reset()         { *m = DirectBoot{} }
func (m *DirectBoot) String() string { return proto.CompactTextString(m) }
func (*DirectBoot) ProtoMessage()    {}
func (*DirectBoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{0}
}

func (m *DirectBoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectBoot.Unmarshal(m, b)
}
func (m *DirectBoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectBoot.Marshal(b, m, deterministic)
}
func (m *DirectBoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectBoot.Merge(m, src)
}
func (m *DirectBoot) XXX_Size() int {
	return xxx_messageInfo_DirectBoot.Size(m)
}
func (m *DirectBoot) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectBoot.DiscardUnknown(m)
}

var xxx_messageInfo_DirectBoot proto.InternalMessageInfo

func (m *DirectBoot) GetKernelPath() string {
	if m != nil {
		return m.KernelPath
	}
	return ""
}

func (m *DirectBoot) GetInitrdPath() string {
	if m != nil {
		return m.InitrdPath
	}
	return ""
}

func (m *DirectBoot) GetKernelCmdline() string {
	if m != nil {
		return m.KernelCmdline
	}
	return ""
}

type UEFI struct {
	FirmwarePath string `protobuf:"bytes,1,opt,name=firmware_path,json=firmwarePath,proto3" json:"firmware_path,omitempty"`
	DevicePath   string `protobuf:"bytes,2,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	// Optional data to include for uefi boot. For Linux this could be used as the kernel
	// commandline.
	OptionalData         string   `protobuf:"bytes,3,opt,name=optional_data,json=optionalData,proto3" json:"optional_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UEFI) Reset()         { *m = UEFI{} }
func (m *UEFI) String() string { return proto.CompactTextString(m) }
func (*UEFI) ProtoMessage()    {}
func (*UEFI) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{1}
}

func (m *UEFI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UEFI.Unmarshal(m, b)
}
func (m *UEFI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UEFI.Marshal(b, m, deterministic)
}
func (m *UEFI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UEFI.Merge(m, src)
}
func (m *UEFI) XXX_Size() int {
	return xxx_messageInfo_UEFI.Size(m)
}
func (m *UEFI) XXX_DiscardUnknown() {
	xxx_messageInfo_UEFI.DiscardUnknown(m)
}

var xxx_messageInfo_UEFI proto.InternalMessageInfo

func (m *UEFI) GetFirmwarePath() string {
	if m != nil {
		return m.FirmwarePath
	}
	return ""
}

func (m *UEFI) GetDevicePath() string {
	if m != nil {
		return m.DevicePath
	}
	return ""
}

func (m *UEFI) GetOptionalData() string {
	if m != nil {
		return m.OptionalData
	}
	return ""
}

type MemoryConfig struct {
	MemoryMb             uint64   `protobuf:"varint,1,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	AllowOvercommit      bool     `protobuf:"varint,2,opt,name=allow_overcommit,json=allowOvercommit,proto3" json:"allow_overcommit,omitempty"`
	DeferredCommit       bool     `protobuf:"varint,3,opt,name=deferred_commit,json=deferredCommit,proto3" json:"deferred_commit,omitempty"`
	HotHint              bool     `protobuf:"varint,4,opt,name=hot_hint,json=hotHint,proto3" json:"hot_hint,omitempty"`
	ColdHint             bool     `protobuf:"varint,5,opt,name=cold_hint,json=coldHint,proto3" json:"cold_hint,omitempty"`
	ColdDiscardHint      bool     `protobuf:"varint,6,opt,name=cold_discard_hint,json=coldDiscardHint,proto3" json:"cold_discard_hint,omitempty"`
	LowMmioGapInMb       uint64   `protobuf:"varint,7,opt,name=low_mmio_gap_in_mb,json=lowMmioGapInMb,proto3" json:"low_mmio_gap_in_mb,omitempty"`
	HighMmioBaseInMb     uint64   `protobuf:"varint,8,opt,name=high_mmio_base_in_mb,json=highMmioBaseInMb,proto3" json:"high_mmio_base_in_mb,omitempty"`
	HighMmioGapInMb      uint64   `protobuf:"varint,9,opt,name=high_mmio_gap_in_mb,json=highMmioGapInMb,proto3" json:"high_mmio_gap_in_mb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryConfig) Reset()         { *m = MemoryConfig{} }
func (m *MemoryConfig) String() string { return proto.CompactTextString(m) }
func (*MemoryConfig) ProtoMessage()    {}
func (*MemoryConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{2}
}

func (m *MemoryConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryConfig.Unmarshal(m, b)
}
func (m *MemoryConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryConfig.Marshal(b, m, deterministic)
}
func (m *MemoryConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryConfig.Merge(m, src)
}
func (m *MemoryConfig) XXX_Size() int {
	return xxx_messageInfo_MemoryConfig.Size(m)
}
func (m *MemoryConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryConfig proto.InternalMessageInfo

func (m *MemoryConfig) GetMemoryMb() uint64 {
	if m != nil {
		return m.MemoryMb
	}
	return 0
}

func (m *MemoryConfig) GetAllowOvercommit() bool {
	if m != nil {
		return m.AllowOvercommit
	}
	return false
}

func (m *MemoryConfig) GetDeferredCommit() bool {
	if m != nil {
		return m.DeferredCommit
	}
	return false
}

func (m *MemoryConfig) GetHotHint() bool {
	if m != nil {
		return m.HotHint
	}
	return false
}

func (m *MemoryConfig) GetColdHint() bool {
	if m != nil {
		return m.ColdHint
	}
	return false
}

func (m *MemoryConfig) GetColdDiscardHint() bool {
	if m != nil {
		return m.ColdDiscardHint
	}
	return false
}

func (m *MemoryConfig) GetLowMmioGapInMb() uint64 {
	if m != nil {
		return m.LowMmioGapInMb
	}
	return 0
}

func (m *MemoryConfig) GetHighMmioBaseInMb() uint64 {
	if m != nil {
		return m.HighMmioBaseInMb
	}
	return 0
}

func (m *MemoryConfig) GetHighMmioGapInMb() uint64 {
	if m != nil {
		return m.HighMmioGapInMb
	}
	return 0
}

type ProcessorConfig struct {
	ProcessorCount       uint32   `protobuf:"varint,1,opt,name=processor_count,json=processorCount,proto3" json:"processor_count,omitempty"`
	ProcessorWeight      uint32   `protobuf:"varint,2,opt,name=processor_weight,json=processorWeight,proto3" json:"processor_weight,omitempty"`
	ProcessorLimit       uint32   `protobuf:"varint,3,opt,name=processor_limit,json=processorLimit,proto3" json:"processor_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessorConfig) Reset()         { *m = ProcessorConfig{} }
func (m *ProcessorConfig) String() string { return proto.CompactTextString(m) }
func (*ProcessorConfig) ProtoMessage()    {}
func (*ProcessorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{3}
}

func (m *ProcessorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessorConfig.Unmarshal(m, b)
}
func (m *ProcessorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessorConfig.Marshal(b, m, deterministic)
}
func (m *ProcessorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorConfig.Merge(m, src)
}
func (m *ProcessorConfig) XXX_Size() int {
	return xxx_messageInfo_ProcessorConfig.Size(m)
}
func (m *ProcessorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorConfig proto.InternalMessageInfo

func (m *ProcessorConfig) GetProcessorCount() uint32 {
	if m != nil {
		return m.ProcessorCount
	}
	return 0
}

func (m *ProcessorConfig) GetProcessorWeight() uint32 {
	if m != nil {
		return m.ProcessorWeight
	}
	return 0
}

func (m *ProcessorConfig) GetProcessorLimit() uint32 {
	if m != nil {
		return m.ProcessorLimit
	}
	return 0
}

type DevicesConfig struct {
	ScsiDisks  []*SCSIDisk  `protobuf:"bytes,1,rep,name=scsi_disks,json=scsiDisks,proto3" json:"scsi_disks,omitempty"`
	VpmemDisks []*VPMEMDisk `protobuf:"bytes,2,rep,name=vpmem_disks,json=vpmemDisks,proto3" json:"vpmem_disks,omitempty"`
	NicConfig  []*NICConfig `protobuf:"bytes,3,rep,name=nic_config,json=nicConfig,proto3" json:"nic_config,omitempty"`
	// When we know what information we need to assign a pci device on Linux,
	// have a oneof here named PCIDevice with WindowsPCIDevice and LinuxPCIDevice
	// housed.
	WindowsDevice        []*WindowsPCIDevice `protobuf:"bytes,4,rep,name=windows_device,json=windowsDevice,proto3" json:"windows_device,omitempty"`
	VirtiofsConfig       []*VirtioFSConfig   `protobuf:"bytes,5,rep,name=virtiofs_config,json=virtiofsConfig,proto3" json:"virtiofs_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DevicesConfig) Reset()         { *m = DevicesConfig{} }
func (m *DevicesConfig) String() string { return proto.CompactTextString(m) }
func (*DevicesConfig) ProtoMessage()    {}
func (*DevicesConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{4}
}

func (m *DevicesConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevicesConfig.Unmarshal(m, b)
}
func (m *DevicesConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevicesConfig.Marshal(b, m, deterministic)
}
func (m *DevicesConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevicesConfig.Merge(m, src)
}
func (m *DevicesConfig) XXX_Size() int {
	return xxx_messageInfo_DevicesConfig.Size(m)
}
func (m *DevicesConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DevicesConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DevicesConfig proto.InternalMessageInfo

func (m *DevicesConfig) GetScsiDisks() []*SCSIDisk {
	if m != nil {
		return m.ScsiDisks
	}
	return nil
}

func (m *DevicesConfig) GetVpmemDisks() []*VPMEMDisk {
	if m != nil {
		return m.VpmemDisks
	}
	return nil
}

func (m *DevicesConfig) GetNicConfig() []*NICConfig {
	if m != nil {
		return m.NicConfig
	}
	return nil
}

func (m *DevicesConfig) GetWindowsDevice() []*WindowsPCIDevice {
	if m != nil {
		return m.WindowsDevice
	}
	return nil
}

func (m *DevicesConfig) GetVirtiofsConfig() []*VirtioFSConfig {
	if m != nil {
		return m.VirtiofsConfig
	}
	return nil
}

type VMConfig struct {
	MemoryConfig    *MemoryConfig    `protobuf:"bytes,1,opt,name=memory_config,json=memoryConfig,proto3" json:"memory_config,omitempty"`
	ProcessorConfig *ProcessorConfig `protobuf:"bytes,2,opt,name=processor_config,json=processorConfig,proto3" json:"processor_config,omitempty"`
	DevicesConfig   *DevicesConfig   `protobuf:"bytes,3,opt,name=devices_config,json=devicesConfig,proto3" json:"devices_config,omitempty"`
	SerialConfig    *SerialConfig    `protobuf:"bytes,4,opt,name=serial_config,json=serialConfig,proto3" json:"serial_config,omitempty"`
	// Types that are valid to be assigned to BootConfig:
	//	*VMConfig_DirectBoot
	//	*VMConfig_Uefi
	BootConfig     isVMConfig_BootConfig `protobuf_oneof:"BootConfig"`
	WindowsOptions *WindowsOptions       `protobuf:"bytes,7,opt,name=windows_options,json=windowsOptions,proto3" json:"windows_options,omitempty"`
	// Optional k:v extra data. Up to the virtstack for how to interpret this.
	ExtraData            map[string]string `protobuf:"bytes,8,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HvsocketConfig       *HVSocketConfig   `protobuf:"bytes,9,opt,name=hvsocket_config,json=hvsocketConfig,proto3" json:"hvsocket_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VMConfig) Reset()         { *m = VMConfig{} }
func (m *VMConfig) String() string { return proto.CompactTextString(m) }
func (*VMConfig) ProtoMessage()    {}
func (*VMConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{5}
}

func (m *VMConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VMConfig.Unmarshal(m, b)
}
func (m *VMConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VMConfig.Marshal(b, m, deterministic)
}
func (m *VMConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VMConfig.Merge(m, src)
}
func (m *VMConfig) XXX_Size() int {
	return xxx_messageInfo_VMConfig.Size(m)
}
func (m *VMConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_VMConfig.DiscardUnknown(m)
}

var xxx_messageInfo_VMConfig proto.InternalMessageInfo

func (m *VMConfig) GetMemoryConfig() *MemoryConfig {
	if m != nil {
		return m.MemoryConfig
	}
	return nil
}

func (m *VMConfig) GetProcessorConfig() *ProcessorConfig {
	if m != nil {
		return m.ProcessorConfig
	}
	return nil
}

func (m *VMConfig) GetDevicesConfig() *DevicesConfig {
	if m != nil {
		return m.DevicesConfig
	}
	return nil
}

func (m *VMConfig) GetSerialConfig() *SerialConfig {
	if m != nil {
		return m.SerialConfig
	}
	return nil
}

type isVMConfig_BootConfig interface {
	isVMConfig_BootConfig()
}

type VMConfig_DirectBoot struct {
	DirectBoot *DirectBoot `protobuf:"bytes,5,opt,name=direct_boot,json=directBoot,proto3,oneof"`
}

type VMConfig_Uefi struct {
	Uefi *UEFI `protobuf:"bytes,6,opt,name=uefi,proto3,oneof"`
}

func (*VMConfig_DirectBoot) isVMConfig_BootConfig() {}

func (*VMConfig_Uefi) isVMConfig_BootConfig() {}

func (m *VMConfig) GetBootConfig() isVMConfig_BootConfig {
	if m != nil {
		return m.BootConfig
	}
	return nil
}

func (m *VMConfig) GetDirectBoot() *DirectBoot {
	if x, ok := m.GetBootConfig().(*VMConfig_DirectBoot); ok {
		return x.DirectBoot
	}
	return nil
}

func (m *VMConfig) GetUefi() *UEFI {
	if x, ok := m.GetBootConfig().(*VMConfig_Uefi); ok {
		return x.Uefi
	}
	return nil
}

func (m *VMConfig) GetWindowsOptions() *WindowsOptions {
	if m != nil {
		return m.WindowsOptions
	}
	return nil
}

func (m *VMConfig) GetExtraData() map[string]string {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *VMConfig) GetHvsocketConfig() *HVSocketConfig {
	if m != nil {
		return m.HvsocketConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*VMConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*VMConfig_DirectBoot)(nil),
		(*VMConfig_Uefi)(nil),
	}
}

// WindowsOptions contains virtual machine configurations that are only present on a Windows host.
type WindowsOptions struct {
	CpuGroupId           uint64   `protobuf:"varint,1,opt,name=cpu_group_id,json=cpuGroupId,proto3" json:"cpu_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WindowsOptions) Reset()         { *m = WindowsOptions{} }
func (m *WindowsOptions) String() string { return proto.CompactTextString(m) }
func (*WindowsOptions) ProtoMessage()    {}
func (*WindowsOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{6}
}

func (m *WindowsOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindowsOptions.Unmarshal(m, b)
}
func (m *WindowsOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindowsOptions.Marshal(b, m, deterministic)
}
func (m *WindowsOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowsOptions.Merge(m, src)
}
func (m *WindowsOptions) XXX_Size() int {
	return xxx_messageInfo_WindowsOptions.Size(m)
}
func (m *WindowsOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowsOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WindowsOptions proto.InternalMessageInfo

func (m *WindowsOptions) GetCpuGroupId() uint64 {
	if m != nil {
		return m.CpuGroupId
	}
	return 0
}

type SerialConfig struct {
	Ports                []*SerialConfig_Config `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SerialConfig) Reset()         { *m = SerialConfig{} }
func (m *SerialConfig) String() string { return proto.CompactTextString(m) }
func (*SerialConfig) ProtoMessage()    {}
func (*SerialConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{7}
}

func (m *SerialConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerialConfig.Unmarshal(m, b)
}
func (m *SerialConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerialConfig.Marshal(b, m, deterministic)
}
func (m *SerialConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerialConfig.Merge(m, src)
}
func (m *SerialConfig) XXX_Size() int {
	return xxx_messageInfo_SerialConfig.Size(m)
}
func (m *SerialConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SerialConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SerialConfig proto.InternalMessageInfo

func (m *SerialConfig) GetPorts() []*SerialConfig_Config {
	if m != nil {
		return m.Ports
	}
	return nil
}

type SerialConfig_Config struct {
	Port uint32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// Uds to relay serial console output to.
	SocketPath           string   `protobuf:"bytes,2,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerialConfig_Config) Reset()         { *m = SerialConfig_Config{} }
func (m *SerialConfig_Config) String() string { return proto.CompactTextString(m) }
func (*SerialConfig_Config) ProtoMessage()    {}
func (*SerialConfig_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{7, 0}
}

func (m *SerialConfig_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerialConfig_Config.Unmarshal(m, b)
}
func (m *SerialConfig_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerialConfig_Config.Marshal(b, m, deterministic)
}
func (m *SerialConfig_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerialConfig_Config.Merge(m, src)
}
func (m *SerialConfig_Config) XXX_Size() int {
	return xxx_messageInfo_SerialConfig_Config.Size(m)
}
func (m *SerialConfig_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_SerialConfig_Config.DiscardUnknown(m)
}

var xxx_messageInfo_SerialConfig_Config proto.InternalMessageInfo

func (m *SerialConfig_Config) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SerialConfig_Config) GetSocketPath() string {
	if m != nil {
		return m.SocketPath
	}
	return ""
}

type HVSocketConfig struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HVSocketConfig) Reset()         { *m = HVSocketConfig{} }
func (m *HVSocketConfig) String() string { return proto.CompactTextString(m) }
func (*HVSocketConfig) ProtoMessage()    {}
func (*HVSocketConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{8}
}

func (m *HVSocketConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HVSocketConfig.Unmarshal(m, b)
}
func (m *HVSocketConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HVSocketConfig.Marshal(b, m, deterministic)
}
func (m *HVSocketConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HVSocketConfig.Merge(m, src)
}
func (m *HVSocketConfig) XXX_Size() int {
	return xxx_messageInfo_HVSocketConfig.Size(m)
}
func (m *HVSocketConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HVSocketConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HVSocketConfig proto.InternalMessageInfo

func (m *HVSocketConfig) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type CreateVMRequest struct {
	Config *VMConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Optional ID to be used by the VM service in log messages. It's up to the
	// server/virtstack to make use of this field. Useful for debugging to be able to
	// correlate events in the virtstack for a given vm that the client launched.
	LogId                string   `protobuf:"bytes,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVMRequest) Reset()         { *m = CreateVMRequest{} }
func (m *CreateVMRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVMRequest) ProtoMessage()    {}
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{9}
}

func (m *CreateVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVMRequest.Unmarshal(m, b)
}
func (m *CreateVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVMRequest.Marshal(b, m, deterministic)
}
func (m *CreateVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVMRequest.Merge(m, src)
}
func (m *CreateVMRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVMRequest.Size(m)
}
func (m *CreateVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVMRequest proto.InternalMessageInfo

func (m *CreateVMRequest) GetConfig() *VMConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *CreateVMRequest) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

type MemoryStats struct {
	WorkingSetBytes      uint64   `protobuf:"varint,1,opt,name=working_set_bytes,json=workingSetBytes,proto3" json:"working_set_bytes,omitempty"`
	AvailableMemory      uint64   `protobuf:"varint,2,opt,name=available_memory,json=availableMemory,proto3" json:"available_memory,omitempty"`
	ReservedMemory       uint64   `protobuf:"varint,3,opt,name=reserved_memory,json=reservedMemory,proto3" json:"reserved_memory,omitempty"`
	AssignedMemory       uint64   `protobuf:"varint,4,opt,name=assigned_memory,json=assignedMemory,proto3" json:"assigned_memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryStats) Reset()         { *m = MemoryStats{} }
func (m *MemoryStats) String() string { return proto.CompactTextString(m) }
func (*MemoryStats) ProtoMessage()    {}
func (*MemoryStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{10}
}

func (m *MemoryStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryStats.Unmarshal(m, b)
}
func (m *MemoryStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryStats.Marshal(b, m, deterministic)
}
func (m *MemoryStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryStats.Merge(m, src)
}
func (m *MemoryStats) XXX_Size() int {
	return xxx_messageInfo_MemoryStats.Size(m)
}
func (m *MemoryStats) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryStats.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryStats proto.InternalMessageInfo

func (m *MemoryStats) GetWorkingSetBytes() uint64 {
	if m != nil {
		return m.WorkingSetBytes
	}
	return 0
}

func (m *MemoryStats) GetAvailableMemory() uint64 {
	if m != nil {
		return m.AvailableMemory
	}
	return 0
}

func (m *MemoryStats) GetReservedMemory() uint64 {
	if m != nil {
		return m.ReservedMemory
	}
	return 0
}

func (m *MemoryStats) GetAssignedMemory() uint64 {
	if m != nil {
		return m.AssignedMemory
	}
	return 0
}

type ProcessorStats struct {
	TotalRuntimeNs       uint64   `protobuf:"varint,1,opt,name=total_runtime_ns,json=totalRuntimeNs,proto3" json:"total_runtime_ns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessorStats) Reset()         { *m = ProcessorStats{} }
func (m *ProcessorStats) String() string { return proto.CompactTextString(m) }
func (*ProcessorStats) ProtoMessage()    {}
func (*ProcessorStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{11}
}

func (m *ProcessorStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessorStats.Unmarshal(m, b)
}
func (m *ProcessorStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessorStats.Marshal(b, m, deterministic)
}
func (m *ProcessorStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorStats.Merge(m, src)
}
func (m *ProcessorStats) XXX_Size() int {
	return xxx_messageInfo_ProcessorStats.Size(m)
}
func (m *ProcessorStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorStats.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorStats proto.InternalMessageInfo

func (m *ProcessorStats) GetTotalRuntimeNs() uint64 {
	if m != nil {
		return m.TotalRuntimeNs
	}
	return 0
}

type PropertiesVMRequest struct {
	Types                []PropertiesVMRequest_PropertiesType `protobuf:"varint,1,rep,packed,name=types,proto3,enum=vmservice.PropertiesVMRequest_PropertiesType" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *PropertiesVMRequest) Reset()         { *m = PropertiesVMRequest{} }
func (m *PropertiesVMRequest) String() string { return proto.CompactTextString(m) }
func (*PropertiesVMRequest) ProtoMessage()    {}
func (*PropertiesVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{12}
}

func (m *PropertiesVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertiesVMRequest.Unmarshal(m, b)
}
func (m *PropertiesVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertiesVMRequest.Marshal(b, m, deterministic)
}
func (m *PropertiesVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertiesVMRequest.Merge(m, src)
}
func (m *PropertiesVMRequest) XXX_Size() int {
	return xxx_messageInfo_PropertiesVMRequest.Size(m)
}
func (m *PropertiesVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertiesVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PropertiesVMRequest proto.InternalMessageInfo

func (m *PropertiesVMRequest) GetTypes() []PropertiesVMRequest_PropertiesType {
	if m != nil {
		return m.Types
	}
	return nil
}

type PropertiesVMResponse struct {
	MemoryStats          *MemoryStats    `protobuf:"bytes,1,opt,name=memory_stats,json=memoryStats,proto3" json:"memory_stats,omitempty"`
	ProcessorStats       *ProcessorStats `protobuf:"bytes,2,opt,name=processor_stats,json=processorStats,proto3" json:"processor_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PropertiesVMResponse) Reset()         { *m = PropertiesVMResponse{} }
func (m *PropertiesVMResponse) String() string { return proto.CompactTextString(m) }
func (*PropertiesVMResponse) ProtoMessage()    {}
func (*PropertiesVMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{13}
}

func (m *PropertiesVMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertiesVMResponse.Unmarshal(m, b)
}
func (m *PropertiesVMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertiesVMResponse.Marshal(b, m, deterministic)
}
func (m *PropertiesVMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertiesVMResponse.Merge(m, src)
}
func (m *PropertiesVMResponse) XXX_Size() int {
	return xxx_messageInfo_PropertiesVMResponse.Size(m)
}
func (m *PropertiesVMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertiesVMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PropertiesVMResponse proto.InternalMessageInfo

func (m *PropertiesVMResponse) GetMemoryStats() *MemoryStats {
	if m != nil {
		return m.MemoryStats
	}
	return nil
}

func (m *PropertiesVMResponse) GetProcessorStats() *ProcessorStats {
	if m != nil {
		return m.ProcessorStats
	}
	return nil
}

type CapabilitiesVMResponse struct {
	SupportedResources   []*CapabilitiesVMResponse_SupportedResource `protobuf:"bytes,1,rep,name=supported_resources,json=supportedResources,proto3" json:"supported_resources,omitempty"`
	SupportedGuestOs     []CapabilitiesVMResponse_SupportedGuestOS   `protobuf:"varint,2,rep,packed,name=supported_guest_os,json=supportedGuestOs,proto3,enum=vmservice.CapabilitiesVMResponse_SupportedGuestOS" json:"supported_guest_os,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *CapabilitiesVMResponse) Reset()         { *m = CapabilitiesVMResponse{} }
func (m *CapabilitiesVMResponse) String() string { return proto.CompactTextString(m) }
func (*CapabilitiesVMResponse) ProtoMessage()    {}
func (*CapabilitiesVMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{14}
}

func (m *CapabilitiesVMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapabilitiesVMResponse.Unmarshal(m, b)
}
func (m *CapabilitiesVMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapabilitiesVMResponse.Marshal(b, m, deterministic)
}
func (m *CapabilitiesVMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapabilitiesVMResponse.Merge(m, src)
}
func (m *CapabilitiesVMResponse) XXX_Size() int {
	return xxx_messageInfo_CapabilitiesVMResponse.Size(m)
}
func (m *CapabilitiesVMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CapabilitiesVMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CapabilitiesVMResponse proto.InternalMessageInfo

func (m *CapabilitiesVMResponse) GetSupportedResources() []*CapabilitiesVMResponse_SupportedResource {
	if m != nil {
		return m.SupportedResources
	}
	return nil
}

func (m *CapabilitiesVMResponse) GetSupportedGuestOs() []CapabilitiesVMResponse_SupportedGuestOS {
	if m != nil {
		return m.SupportedGuestOs
	}
	return nil
}

type CapabilitiesVMResponse_SupportedResource struct {
	Add                  bool                            `protobuf:"varint,1,opt,name=Add,proto3" json:"Add,omitempty"`
	Remove               bool                            `protobuf:"varint,2,opt,name=Remove,proto3" json:"Remove,omitempty"`
	Update               bool                            `protobuf:"varint,3,opt,name=Update,proto3" json:"Update,omitempty"`
	Resource             CapabilitiesVMResponse_Resource `protobuf:"varint,4,opt,name=resource,proto3,enum=vmservice.CapabilitiesVMResponse_Resource" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *CapabilitiesVMResponse_SupportedResource) Reset() {
	*m = CapabilitiesVMResponse_SupportedResource{}
}
func (m *CapabilitiesVMResponse_SupportedResource) String() string { return proto.CompactTextString(m) }
func (*CapabilitiesVMResponse_SupportedResource) ProtoMessage()    {}
func (*CapabilitiesVMResponse_SupportedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{14, 0}
}

func (m *CapabilitiesVMResponse_SupportedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapabilitiesVMResponse_SupportedResource.Unmarshal(m, b)
}
func (m *CapabilitiesVMResponse_SupportedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapabilitiesVMResponse_SupportedResource.Marshal(b, m, deterministic)
}
func (m *CapabilitiesVMResponse_SupportedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapabilitiesVMResponse_SupportedResource.Merge(m, src)
}
func (m *CapabilitiesVMResponse_SupportedResource) XXX_Size() int {
	return xxx_messageInfo_CapabilitiesVMResponse_SupportedResource.Size(m)
}
func (m *CapabilitiesVMResponse_SupportedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_CapabilitiesVMResponse_SupportedResource.DiscardUnknown(m)
}

var xxx_messageInfo_CapabilitiesVMResponse_SupportedResource proto.InternalMessageInfo

func (m *CapabilitiesVMResponse_SupportedResource) GetAdd() bool {
	if m != nil {
		return m.Add
	}
	return false
}

func (m *CapabilitiesVMResponse_SupportedResource) GetRemove() bool {
	if m != nil {
		return m.Remove
	}
	return false
}

func (m *CapabilitiesVMResponse_SupportedResource) GetUpdate() bool {
	if m != nil {
		return m.Update
	}
	return false
}

func (m *CapabilitiesVMResponse_SupportedResource) GetResource() CapabilitiesVMResponse_Resource {
	if m != nil {
		return m.Resource
	}
	return CapabilitiesVMResponse_Vpmem
}

type SCSIDisk struct {
	Controller           uint32   `protobuf:"varint,1,opt,name=controller,proto3" json:"controller,omitempty"`
	Lun                  uint32   `protobuf:"varint,2,opt,name=lun,proto3" json:"lun,omitempty"`
	HostPath             string   `protobuf:"bytes,3,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	Type                 DiskType `protobuf:"varint,4,opt,name=type,proto3,enum=vmservice.DiskType" json:"type,omitempty"`
	ReadOnly             bool     `protobuf:"varint,5,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCSIDisk) Reset()         { *m = SCSIDisk{} }
func (m *SCSIDisk) String() string { return proto.CompactTextString(m) }
func (*SCSIDisk) ProtoMessage()    {}
func (*SCSIDisk) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{15}
}

func (m *SCSIDisk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCSIDisk.Unmarshal(m, b)
}
func (m *SCSIDisk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCSIDisk.Marshal(b, m, deterministic)
}
func (m *SCSIDisk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCSIDisk.Merge(m, src)
}
func (m *SCSIDisk) XXX_Size() int {
	return xxx_messageInfo_SCSIDisk.Size(m)
}
func (m *SCSIDisk) XXX_DiscardUnknown() {
	xxx_messageInfo_SCSIDisk.DiscardUnknown(m)
}

var xxx_messageInfo_SCSIDisk proto.InternalMessageInfo

func (m *SCSIDisk) GetController() uint32 {
	if m != nil {
		return m.Controller
	}
	return 0
}

func (m *SCSIDisk) GetLun() uint32 {
	if m != nil {
		return m.Lun
	}
	return 0
}

func (m *SCSIDisk) GetHostPath() string {
	if m != nil {
		return m.HostPath
	}
	return ""
}

func (m *SCSIDisk) GetType() DiskType {
	if m != nil {
		return m.Type
	}
	return DiskType_SCSI_DISK_TYPE_VHD1
}

func (m *SCSIDisk) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

type VPMEMDisk struct {
	HostPath             string   `protobuf:"bytes,1,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	Type                 DiskType `protobuf:"varint,2,opt,name=type,proto3,enum=vmservice.DiskType" json:"type,omitempty"`
	ReadOnly             bool     `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPMEMDisk) Reset()         { *m = VPMEMDisk{} }
func (m *VPMEMDisk) String() string { return proto.CompactTextString(m) }
func (*VPMEMDisk) ProtoMessage()    {}
func (*VPMEMDisk) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{16}
}

func (m *VPMEMDisk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPMEMDisk.Unmarshal(m, b)
}
func (m *VPMEMDisk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPMEMDisk.Marshal(b, m, deterministic)
}
func (m *VPMEMDisk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPMEMDisk.Merge(m, src)
}
func (m *VPMEMDisk) XXX_Size() int {
	return xxx_messageInfo_VPMEMDisk.Size(m)
}
func (m *VPMEMDisk) XXX_DiscardUnknown() {
	xxx_messageInfo_VPMEMDisk.DiscardUnknown(m)
}

var xxx_messageInfo_VPMEMDisk proto.InternalMessageInfo

func (m *VPMEMDisk) GetHostPath() string {
	if m != nil {
		return m.HostPath
	}
	return ""
}

func (m *VPMEMDisk) GetType() DiskType {
	if m != nil {
		return m.Type
	}
	return DiskType_SCSI_DISK_TYPE_VHD1
}

func (m *VPMEMDisk) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

type NICConfig struct {
	NicId          string `protobuf:"bytes,1,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"`
	MacAddress     string `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	LegacySwitchId string `protobuf:"bytes,4,opt,name=legacy_switch_id,json=legacySwitchId,proto3" json:"legacy_switch_id,omitempty"`
	// Optional friendly name for the adapter. Might be useful to show up in logs.
	NicName string `protobuf:"bytes,5,opt,name=nic_name,json=nicName,proto3" json:"nic_name,omitempty"`
	// Types that are valid to be assigned to Backend:
	//	*NICConfig_LegacyPortId
	//	*NICConfig_Dio
	//	*NICConfig_Tap
	Backend              isNICConfig_Backend `protobuf_oneof:"backend"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NICConfig) Reset()         { *m = NICConfig{} }
func (m *NICConfig) String() string { return proto.CompactTextString(m) }
func (*NICConfig) ProtoMessage()    {}
func (*NICConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{17}
}

func (m *NICConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NICConfig.Unmarshal(m, b)
}
func (m *NICConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NICConfig.Marshal(b, m, deterministic)
}
func (m *NICConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NICConfig.Merge(m, src)
}
func (m *NICConfig) XXX_Size() int {
	return xxx_messageInfo_NICConfig.Size(m)
}
func (m *NICConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NICConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NICConfig proto.InternalMessageInfo

func (m *NICConfig) GetNicId() string {
	if m != nil {
		return m.NicId
	}
	return ""
}

func (m *NICConfig) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *NICConfig) GetLegacySwitchId() string {
	if m != nil {
		return m.LegacySwitchId
	}
	return ""
}

func (m *NICConfig) GetNicName() string {
	if m != nil {
		return m.NicName
	}
	return ""
}

type isNICConfig_Backend interface {
	isNICConfig_Backend()
}

type NICConfig_LegacyPortId struct {
	LegacyPortId string `protobuf:"bytes,2,opt,name=legacy_port_id,json=legacyPortId,proto3,oneof"`
}

type NICConfig_Dio struct {
	Dio *DioBackend `protobuf:"bytes,6,opt,name=dio,proto3,oneof"`
}

type NICConfig_Tap struct {
	Tap *TapBackend `protobuf:"bytes,7,opt,name=tap,proto3,oneof"`
}

func (*NICConfig_LegacyPortId) isNICConfig_Backend() {}

func (*NICConfig_Dio) isNICConfig_Backend() {}

func (*NICConfig_Tap) isNICConfig_Backend() {}

func (m *NICConfig) GetBackend() isNICConfig_Backend {
	if m != nil {
		return m.Backend
	}
	return nil
}

func (m *NICConfig) GetLegacyPortId() string {
	if x, ok := m.GetBackend().(*NICConfig_LegacyPortId); ok {
		return x.LegacyPortId
	}
	return ""
}

func (m *NICConfig) GetDio() *DioBackend {
	if x, ok := m.GetBackend().(*NICConfig_Dio); ok {
		return x.Dio
	}
	return nil
}

func (m *NICConfig) GetTap() *TapBackend {
	if x, ok := m.GetBackend().(*NICConfig_Tap); ok {
		return x.Tap
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NICConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NICConfig_LegacyPortId)(nil),
		(*NICConfig_Dio)(nil),
		(*NICConfig_Tap)(nil),
	}
}

type DioBackend struct {
	SwitchId             string   `protobuf:"bytes,1,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	PortId               string   `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DioBackend) Reset()         { *m = DioBackend{} }
func (m *DioBackend) String() string { return proto.CompactTextString(m) }
func (*DioBackend) ProtoMessage()    {}
func (*DioBackend) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{18}
}

func (m *DioBackend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DioBackend.Unmarshal(m, b)
}
func (m *DioBackend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DioBackend.Marshal(b, m, deterministic)
}
func (m *DioBackend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DioBackend.Merge(m, src)
}
func (m *DioBackend) XXX_Size() int {
	return xxx_messageInfo_DioBackend.Size(m)
}
func (m *DioBackend) XXX_DiscardUnknown() {
	xxx_messageInfo_DioBackend.DiscardUnknown(m)
}

var xxx_messageInfo_DioBackend proto.InternalMessageInfo

func (m *DioBackend) GetSwitchId() string {
	if m != nil {
		return m.SwitchId
	}
	return ""
}

func (m *DioBackend) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

type TapBackend struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TapBackend) Reset()         { *m = TapBackend{} }
func (m *TapBackend) String() string { return proto.CompactTextString(m) }
func (*TapBackend) ProtoMessage()    {}
func (*TapBackend) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{19}
}

func (m *TapBackend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TapBackend.Unmarshal(m, b)
}
func (m *TapBackend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TapBackend.Marshal(b, m, deterministic)
}
func (m *TapBackend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TapBackend.Merge(m, src)
}
func (m *TapBackend) XXX_Size() int {
	return xxx_messageInfo_TapBackend.Size(m)
}
func (m *TapBackend) XXX_DiscardUnknown() {
	xxx_messageInfo_TapBackend.DiscardUnknown(m)
}

var xxx_messageInfo_TapBackend proto.InternalMessageInfo

func (m *TapBackend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type WindowsPCIDevice struct {
	// e.g. PCIP\\VEN_10DE&DEV_13F2&SUBSYS_115E10DE&REV_A1\\6&17F903&0&00400000
	InstanceId           string   `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WindowsPCIDevice) Reset()         { *m = WindowsPCIDevice{} }
func (m *WindowsPCIDevice) String() string { return proto.CompactTextString(m) }
func (*WindowsPCIDevice) ProtoMessage()    {}
func (*WindowsPCIDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{20}
}

func (m *WindowsPCIDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindowsPCIDevice.Unmarshal(m, b)
}
func (m *WindowsPCIDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindowsPCIDevice.Marshal(b, m, deterministic)
}
func (m *WindowsPCIDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowsPCIDevice.Merge(m, src)
}
func (m *WindowsPCIDevice) XXX_Size() int {
	return xxx_messageInfo_WindowsPCIDevice.Size(m)
}
func (m *WindowsPCIDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowsPCIDevice.DiscardUnknown(m)
}

var xxx_messageInfo_WindowsPCIDevice proto.InternalMessageInfo

func (m *WindowsPCIDevice) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type VirtioFSConfig struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	RootPath             string   `protobuf:"bytes,2,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtioFSConfig) Reset()         { *m = VirtioFSConfig{} }
func (m *VirtioFSConfig) String() string { return proto.CompactTextString(m) }
func (*VirtioFSConfig) ProtoMessage()    {}
func (*VirtioFSConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{21}
}

func (m *VirtioFSConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtioFSConfig.Unmarshal(m, b)
}
func (m *VirtioFSConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtioFSConfig.Marshal(b, m, deterministic)
}
func (m *VirtioFSConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtioFSConfig.Merge(m, src)
}
func (m *VirtioFSConfig) XXX_Size() int {
	return xxx_messageInfo_VirtioFSConfig.Size(m)
}
func (m *VirtioFSConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtioFSConfig.DiscardUnknown(m)
}

var xxx_messageInfo_VirtioFSConfig proto.InternalMessageInfo

func (m *VirtioFSConfig) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *VirtioFSConfig) GetRootPath() string {
	if m != nil {
		return m.RootPath
	}
	return ""
}

type ModifyMemoryRequest struct {
	MemoryMb             uint64   `protobuf:"varint,1,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyMemoryRequest) Reset()         { *m = ModifyMemoryRequest{} }
func (m *ModifyMemoryRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyMemoryRequest) ProtoMessage()    {}
func (*ModifyMemoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{22}
}

func (m *ModifyMemoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyMemoryRequest.Unmarshal(m, b)
}
func (m *ModifyMemoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyMemoryRequest.Marshal(b, m, deterministic)
}
func (m *ModifyMemoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyMemoryRequest.Merge(m, src)
}
func (m *ModifyMemoryRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyMemoryRequest.Size(m)
}
func (m *ModifyMemoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyMemoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyMemoryRequest proto.InternalMessageInfo

func (m *ModifyMemoryRequest) GetMemoryMb() uint64 {
	if m != nil {
		return m.MemoryMb
	}
	return 0
}

type ModifyProcessorRequest struct {
	// Index of the processor to add/remove
	ProcessorIndex       uint32   `protobuf:"varint,1,opt,name=processor_index,json=processorIndex,proto3" json:"processor_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyProcessorRequest) Reset()         { *m = ModifyProcessorRequest{} }
func (m *ModifyProcessorRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyProcessorRequest) ProtoMessage()    {}
func (*ModifyProcessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{23}
}

func (m *ModifyProcessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyProcessorRequest.Unmarshal(m, b)
}
func (m *ModifyProcessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyProcessorRequest.Marshal(b, m, deterministic)
}
func (m *ModifyProcessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyProcessorRequest.Merge(m, src)
}
func (m *ModifyProcessorRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyProcessorRequest.Size(m)
}
func (m *ModifyProcessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyProcessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyProcessorRequest proto.InternalMessageInfo

func (m *ModifyProcessorRequest) GetProcessorIndex() uint32 {
	if m != nil {
		return m.ProcessorIndex
	}
	return 0
}

type ModifyProcessorConfigRequest struct {
	ProcessorWeight      uint32   `protobuf:"varint,1,opt,name=processor_weight,json=processorWeight,proto3" json:"processor_weight,omitempty"`
	ProcessorLimit       uint32   `protobuf:"varint,2,opt,name=processor_limit,json=processorLimit,proto3" json:"processor_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyProcessorConfigRequest) Reset()         { *m = ModifyProcessorConfigRequest{} }
func (m *ModifyProcessorConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyProcessorConfigRequest) ProtoMessage()    {}
func (*ModifyProcessorConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{24}
}

func (m *ModifyProcessorConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyProcessorConfigRequest.Unmarshal(m, b)
}
func (m *ModifyProcessorConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyProcessorConfigRequest.Marshal(b, m, deterministic)
}
func (m *ModifyProcessorConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyProcessorConfigRequest.Merge(m, src)
}
func (m *ModifyProcessorConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyProcessorConfigRequest.Size(m)
}
func (m *ModifyProcessorConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyProcessorConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyProcessorConfigRequest proto.InternalMessageInfo

func (m *ModifyProcessorConfigRequest) GetProcessorWeight() uint32 {
	if m != nil {
		return m.ProcessorWeight
	}
	return 0
}

func (m *ModifyProcessorConfigRequest) GetProcessorLimit() uint32 {
	if m != nil {
		return m.ProcessorLimit
	}
	return 0
}

type ModifyResourceRequest struct {
	Type ModifyType `protobuf:"varint,1,opt,name=type,proto3,enum=vmservice.ModifyType" json:"type,omitempty"`
	// Types that are valid to be assigned to Resource:
	//	*ModifyResourceRequest_Processor
	//	*ModifyResourceRequest_ProcessorConfig
	//	*ModifyResourceRequest_Memory
	//	*ModifyResourceRequest_ScsiDisk
	//	*ModifyResourceRequest_VpmemDisk
	//	*ModifyResourceRequest_NicConfig
	//	*ModifyResourceRequest_WindowsDevice
	Resource             isModifyResourceRequest_Resource `protobuf_oneof:"resource"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ModifyResourceRequest) Reset()         { *m = ModifyResourceRequest{} }
func (m *ModifyResourceRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyResourceRequest) ProtoMessage()    {}
func (*ModifyResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2faf75ea50603846, []int{25}
}

func (m *ModifyResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyResourceRequest.Unmarshal(m, b)
}
func (m *ModifyResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyResourceRequest.Marshal(b, m, deterministic)
}
func (m *ModifyResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyResourceRequest.Merge(m, src)
}
func (m *ModifyResourceRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyResourceRequest.Size(m)
}
func (m *ModifyResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyResourceRequest proto.InternalMessageInfo

func (m *ModifyResourceRequest) GetType() ModifyType {
	if m != nil {
		return m.Type
	}
	return ModifyType_ADD
}

type isModifyResourceRequest_Resource interface {
	isModifyResourceRequest_Resource()
}

type ModifyResourceRequest_Processor struct {
	Processor *ModifyProcessorRequest `protobuf:"bytes,2,opt,name=processor,proto3,oneof"`
}

type ModifyResourceRequest_ProcessorConfig struct {
	ProcessorConfig *ModifyProcessorConfigRequest `protobuf:"bytes,3,opt,name=processor_config,json=processorConfig,proto3,oneof"`
}

type ModifyResourceRequest_Memory struct {
	Memory *ModifyMemoryRequest `protobuf:"bytes,4,opt,name=memory,proto3,oneof"`
}

type ModifyResourceRequest_ScsiDisk struct {
	ScsiDisk *SCSIDisk `protobuf:"bytes,5,opt,name=scsi_disk,json=scsiDisk,proto3,oneof"`
}

type ModifyResourceRequest_VpmemDisk struct {
	VpmemDisk *VPMEMDisk `protobuf:"bytes,6,opt,name=vpmem_disk,json=vpmemDisk,proto3,oneof"`
}

type ModifyResourceRequest_NicConfig struct {
	NicConfig *NICConfig `protobuf:"bytes,7,opt,name=nic_config,json=nicConfig,proto3,oneof"`
}

type ModifyResourceRequest_WindowsDevice struct {
	WindowsDevice *WindowsPCIDevice `protobuf:"bytes,8,opt,name=windows_device,json=windowsDevice,proto3,oneof"`
}

func (*ModifyResourceRequest_Processor) isModifyResourceRequest_Resource() {}

func (*ModifyResourceRequest_ProcessorConfig) isModifyResourceRequest_Resource() {}

func (*ModifyResourceRequest_Memory) isModifyResourceRequest_Resource() {}

func (*ModifyResourceRequest_ScsiDisk) isModifyResourceRequest_Resource() {}

func (*ModifyResourceRequest_VpmemDisk) isModifyResourceRequest_Resource() {}

func (*ModifyResourceRequest_NicConfig) isModifyResourceRequest_Resource() {}

func (*ModifyResourceRequest_WindowsDevice) isModifyResourceRequest_Resource() {}

func (m *ModifyResourceRequest) GetResource() isModifyResourceRequest_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ModifyResourceRequest) GetProcessor() *ModifyProcessorRequest {
	if x, ok := m.GetResource().(*ModifyResourceRequest_Processor); ok {
		return x.Processor
	}
	return nil
}

func (m *ModifyResourceRequest) GetProcessorConfig() *ModifyProcessorConfigRequest {
	if x, ok := m.GetResource().(*ModifyResourceRequest_ProcessorConfig); ok {
		return x.ProcessorConfig
	}
	return nil
}

func (m *ModifyResourceRequest) GetMemory() *ModifyMemoryRequest {
	if x, ok := m.GetResource().(*ModifyResourceRequest_Memory); ok {
		return x.Memory
	}
	return nil
}

func (m *ModifyResourceRequest) GetScsiDisk() *SCSIDisk {
	if x, ok := m.GetResource().(*ModifyResourceRequest_ScsiDisk); ok {
		return x.ScsiDisk
	}
	return nil
}

func (m *ModifyResourceRequest) GetVpmemDisk() *VPMEMDisk {
	if x, ok := m.GetResource().(*ModifyResourceRequest_VpmemDisk); ok {
		return x.VpmemDisk
	}
	return nil
}

func (m *ModifyResourceRequest) GetNicConfig() *NICConfig {
	if x, ok := m.GetResource().(*ModifyResourceRequest_NicConfig); ok {
		return x.NicConfig
	}
	return nil
}

func (m *ModifyResourceRequest) GetWindowsDevice() *WindowsPCIDevice {
	if x, ok := m.GetResource().(*ModifyResourceRequest_WindowsDevice); ok {
		return x.WindowsDevice
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ModifyResourceRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ModifyResourceRequest_Processor)(nil),
		(*ModifyResourceRequest_ProcessorConfig)(nil),
		(*ModifyResourceRequest_Memory)(nil),
		(*ModifyResourceRequest_ScsiDisk)(nil),
		(*ModifyResourceRequest_VpmemDisk)(nil),
		(*ModifyResourceRequest_NicConfig)(nil),
		(*ModifyResourceRequest_WindowsDevice)(nil),
	}
}

func init() {
	proto.RegisterEnum("vmservice.ModifyType", ModifyType_name, ModifyType_value)
	proto.RegisterEnum("vmservice.DiskType", DiskType_name, DiskType_value)
	proto.RegisterEnum("vmservice.PropertiesVMRequest_PropertiesType", PropertiesVMRequest_PropertiesType_name, PropertiesVMRequest_PropertiesType_value)
	proto.RegisterEnum("vmservice.CapabilitiesVMResponse_Resource", CapabilitiesVMResponse_Resource_name, CapabilitiesVMResponse_Resource_value)
	proto.RegisterEnum("vmservice.CapabilitiesVMResponse_SupportedGuestOS", CapabilitiesVMResponse_SupportedGuestOS_name, CapabilitiesVMResponse_SupportedGuestOS_value)
	proto.RegisterType((*DirectBoot)(nil), "vmservice.DirectBoot")
	proto.RegisterType((*UEFI)(nil), "vmservice.UEFI")
	proto.RegisterType((*MemoryConfig)(nil), "vmservice.MemoryConfig")
	proto.RegisterType((*ProcessorConfig)(nil), "vmservice.ProcessorConfig")
	proto.RegisterType((*DevicesConfig)(nil), "vmservice.DevicesConfig")
	proto.RegisterType((*VMConfig)(nil), "vmservice.VMConfig")
	proto.RegisterMapType((map[string]string)(nil), "vmservice.VMConfig.ExtraDataEntry")
	proto.RegisterType((*WindowsOptions)(nil), "vmservice.WindowsOptions")
	proto.RegisterType((*SerialConfig)(nil), "vmservice.SerialConfig")
	proto.RegisterType((*SerialConfig_Config)(nil), "vmservice.SerialConfig.Config")
	proto.RegisterType((*HVSocketConfig)(nil), "vmservice.HVSocketConfig")
	proto.RegisterType((*CreateVMRequest)(nil), "vmservice.CreateVMRequest")
	proto.RegisterType((*MemoryStats)(nil), "vmservice.MemoryStats")
	proto.RegisterType((*ProcessorStats)(nil), "vmservice.ProcessorStats")
	proto.RegisterType((*PropertiesVMRequest)(nil), "vmservice.PropertiesVMRequest")
	proto.RegisterType((*PropertiesVMResponse)(nil), "vmservice.PropertiesVMResponse")
	proto.RegisterType((*CapabilitiesVMResponse)(nil), "vmservice.CapabilitiesVMResponse")
	proto.RegisterType((*CapabilitiesVMResponse_SupportedResource)(nil), "vmservice.CapabilitiesVMResponse.SupportedResource")
	proto.RegisterType((*SCSIDisk)(nil), "vmservice.SCSIDisk")
	proto.RegisterType((*VPMEMDisk)(nil), "vmservice.VPMEMDisk")
	proto.RegisterType((*NICConfig)(nil), "vmservice.NICConfig")
	proto.RegisterType((*DioBackend)(nil), "vmservice.DioBackend")
	proto.RegisterType((*TapBackend)(nil), "vmservice.TapBackend")
	proto.RegisterType((*WindowsPCIDevice)(nil), "vmservice.WindowsPCIDevice")
	proto.RegisterType((*VirtioFSConfig)(nil), "vmservice.VirtioFSConfig")
	proto.RegisterType((*ModifyMemoryRequest)(nil), "vmservice.ModifyMemoryRequest")
	proto.RegisterType((*ModifyProcessorRequest)(nil), "vmservice.ModifyProcessorRequest")
	proto.RegisterType((*ModifyProcessorConfigRequest)(nil), "vmservice.ModifyProcessorConfigRequest")
	proto.RegisterType((*ModifyResourceRequest)(nil), "vmservice.ModifyResourceRequest")
}

func init() { proto.RegisterFile("vmservice.proto", fileDescriptor_2faf75ea50603846) }

var fileDescriptor_2faf75ea50603846 = []byte{
	// 2135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xdd, 0x72, 0xdb, 0xc6,
	0x15, 0x26, 0x29, 0x4a, 0x22, 0x8f, 0x44, 0x12, 0x59, 0x39, 0xb6, 0x22, 0x67, 0x12, 0x07, 0x69,
	0xea, 0xc4, 0x69, 0x94, 0x29, 0xdd, 0x74, 0x6c, 0x8f, 0xdb, 0x8c, 0x28, 0xca, 0x26, 0x1b, 0xd3,
	0x62, 0x41, 0x59, 0xae, 0x73, 0x83, 0x2e, 0x81, 0x15, 0xb9, 0x23, 0x00, 0x8b, 0x60, 0x97, 0x92,
	0x79, 0xdd, 0x99, 0xfe, 0xdc, 0x74, 0xa6, 0x17, 0xbd, 0xec, 0xf4, 0x2d, 0xda, 0x27, 0xe9, 0x63,
	0xf4, 0x1d, 0x3a, 0xfb, 0x03, 0x02, 0x20, 0x25, 0xa7, 0xf6, 0x1d, 0xf6, 0xdb, 0xef, 0x9c, 0x3d,
	0x7b, 0x76, 0xf7, 0xfc, 0x00, 0x5a, 0x17, 0x21, 0x27, 0xc9, 0x05, 0xf5, 0xc8, 0x7e, 0x9c, 0x30,
	0xc1, 0x50, 0x7d, 0x01, 0xec, 0xdd, 0x9e, 0x30, 0x36, 0x09, 0xc8, 0xd7, 0x6a, 0x62, 0x3c, 0x3b,
	0xfb, 0x9a, 0x84, 0xb1, 0x98, 0x6b, 0xde, 0xde, 0x87, 0xcb, 0x93, 0x5c, 0x24, 0x33, 0x4f, 0xe8,
	0x59, 0x7b, 0x06, 0xd0, 0xa5, 0x09, 0xf1, 0x44, 0x87, 0x31, 0x81, 0x3e, 0x86, 0xad, 0x73, 0x92,
	0x44, 0x24, 0x70, 0x63, 0x2c, 0xa6, 0xbb, 0xe5, 0x3b, 0xe5, 0xcf, 0xeb, 0x0e, 0x68, 0x68, 0x88,
	0xc5, 0x54, 0x12, 0x68, 0x44, 0x45, 0xe2, 0x6b, 0x42, 0x45, 0x13, 0x34, 0xa4, 0x08, 0x9f, 0x41,
	0xd3, 0x68, 0xf0, 0x42, 0x3f, 0xa0, 0x11, 0xd9, 0x5d, 0x53, 0x9c, 0x86, 0x46, 0x0f, 0x35, 0x68,
	0xff, 0x00, 0xd5, 0x17, 0x47, 0x4f, 0xfa, 0xe8, 0x53, 0x68, 0x9c, 0xd1, 0x24, 0xbc, 0xc4, 0x09,
	0xc9, 0x2f, 0xb9, 0x9d, 0x82, 0xe9, 0xa2, 0x3e, 0x91, 0x1b, 0x2d, 0x2c, 0xaa, 0x21, 0x45, 0xf8,
	0x14, 0x1a, 0x2c, 0x16, 0x94, 0x45, 0x38, 0x70, 0x7d, 0x2c, 0xb0, 0x59, 0x73, 0x3b, 0x05, 0xbb,
	0x58, 0x60, 0xfb, 0xbf, 0x15, 0xd8, 0x1e, 0x90, 0x90, 0x25, 0xf3, 0x43, 0x16, 0x9d, 0xd1, 0x09,
	0xba, 0x0d, 0xf5, 0x50, 0x8d, 0xdd, 0x70, 0xac, 0xd6, 0xad, 0x3a, 0x35, 0x0d, 0x0c, 0xc6, 0xe8,
	0x0b, 0xb0, 0x70, 0x10, 0xb0, 0x4b, 0x97, 0x5d, 0x90, 0xc4, 0x63, 0x61, 0x48, 0x85, 0x5a, 0xb8,
	0xe6, 0xb4, 0x14, 0x7e, 0xbc, 0x80, 0xd1, 0x5d, 0x68, 0xf9, 0xe4, 0x8c, 0x24, 0x09, 0xf1, 0x5d,
	0xc3, 0x5c, 0x53, 0xcc, 0x66, 0x0a, 0x1f, 0x6a, 0xe2, 0x07, 0x50, 0x9b, 0x32, 0xe1, 0x4e, 0x69,
	0x24, 0x76, 0xab, 0x8a, 0xb1, 0x39, 0x65, 0xa2, 0x47, 0x23, 0x21, 0x6d, 0xf1, 0x58, 0xe0, 0xeb,
	0xb9, 0x75, 0x35, 0x57, 0x93, 0x80, 0x9a, 0xbc, 0x07, 0xef, 0xa9, 0x49, 0x9f, 0x72, 0x0f, 0x27,
	0x86, 0xb4, 0xa1, 0x8d, 0x91, 0x13, 0x5d, 0x8d, 0x1b, 0x2e, 0x92, 0x56, 0x87, 0x21, 0x65, 0xee,
	0x04, 0xc7, 0x2e, 0x8d, 0xe4, 0xee, 0x36, 0xd5, 0xee, 0x9a, 0x01, 0xbb, 0x1c, 0x84, 0x94, 0x3d,
	0xc5, 0x71, 0x3f, 0x1a, 0x8c, 0xd1, 0x3e, 0xdc, 0x98, 0xd2, 0xc9, 0x54, 0x93, 0xc7, 0x98, 0x13,
	0xc3, 0xae, 0x29, 0xb6, 0x25, 0xe7, 0x24, 0xbd, 0x83, 0x39, 0x51, 0xfc, 0x9f, 0xc1, 0x4e, 0xc6,
	0xcf, 0x94, 0xd7, 0x15, 0xbd, 0x95, 0xd2, 0x8d, 0x76, 0xfb, 0xaf, 0x65, 0x68, 0x0d, 0x13, 0xe6,
	0x11, 0xce, 0x59, 0x62, 0x5c, 0x7e, 0x17, 0x5a, 0x71, 0x0a, 0xb9, 0x1e, 0x9b, 0x45, 0x42, 0x39,
	0xbe, 0xe1, 0x34, 0xe3, 0x8c, 0x39, 0x8b, 0x84, 0x74, 0x7f, 0x46, 0xbc, 0x24, 0x74, 0x32, 0xd5,
	0xee, 0x6f, 0x38, 0x99, 0x82, 0x97, 0x0a, 0x2e, 0xea, 0x0c, 0x68, 0xea, 0xfe, 0xbc, 0xce, 0x67,
	0x12, 0xb5, 0xff, 0x5d, 0x81, 0x46, 0x57, 0x5d, 0x1a, 0x6e, 0xcc, 0x69, 0x03, 0x70, 0x8f, 0x53,
	0xe9, 0xd8, 0x73, 0xbe, 0x5b, 0xbe, 0xb3, 0xf6, 0xf9, 0x56, 0x7b, 0x67, 0x3f, 0x7b, 0x68, 0xa3,
	0xc3, 0x51, 0xbf, 0x4b, 0xf9, 0xb9, 0x53, 0x97, 0x34, 0xf9, 0xc5, 0xd1, 0x37, 0xb0, 0x75, 0x11,
	0x87, 0x24, 0x34, 0x42, 0x15, 0x25, 0x74, 0x23, 0x27, 0x74, 0x3a, 0x1c, 0x1c, 0x0d, 0x94, 0x14,
	0x28, 0xa2, 0x16, 0xbb, 0x0f, 0x10, 0x51, 0xcf, 0xf5, 0xd4, 0xc2, 0xbb, 0x6b, 0x2b, 0x52, 0xcf,
	0xfb, 0x87, 0xda, 0x28, 0xa7, 0x1e, 0x51, 0xcf, 0xd8, 0xd7, 0x81, 0xe6, 0x25, 0x8d, 0x7c, 0x76,
	0xc9, 0x5d, 0x7d, 0xdb, 0x77, 0xab, 0x4a, 0xf0, 0x76, 0x4e, 0xf0, 0xa5, 0x26, 0x0c, 0x0f, 0xfb,
	0x7a, 0x6f, 0x4e, 0xc3, 0x88, 0xe8, 0x21, 0xea, 0x40, 0xeb, 0x82, 0x26, 0x82, 0xb2, 0x33, 0x9e,
	0xae, 0xbe, 0xae, 0x94, 0x7c, 0x90, 0xb7, 0x59, 0x31, 0x9e, 0x8c, 0x8c, 0x09, 0xcd, 0x54, 0x42,
	0x8f, 0xed, 0x3f, 0xae, 0x43, 0xed, 0x74, 0x60, 0x8c, 0x7a, 0x0c, 0x0d, 0xf3, 0x6c, 0x8c, 0x3a,
	0x79, 0x82, 0x5b, 0xed, 0x5b, 0x39, 0x75, 0xf9, 0x67, 0xe6, 0x6c, 0x87, 0xf9, 0x47, 0x77, 0x94,
	0x3f, 0x58, 0xa3, 0xa0, 0xa2, 0x14, 0xec, 0xe5, 0x14, 0x2c, 0xdd, 0x9b, 0xdc, 0xa1, 0x1b, 0x35,
	0xdf, 0x42, 0x53, 0x7b, 0x84, 0x67, 0x2e, 0x95, 0x4a, 0x76, 0x73, 0x4a, 0x0a, 0x67, 0xed, 0x34,
	0xfc, 0xc2, 0xd1, 0x3f, 0x86, 0x06, 0x27, 0x09, 0xc5, 0x41, 0x2a, 0x5f, 0x5d, 0xd9, 0xc5, 0x48,
	0xcd, 0xa7, 0xbb, 0xe0, 0xb9, 0x11, 0x7a, 0x00, 0x5b, 0xbe, 0x8a, 0x9a, 0xee, 0x98, 0x31, 0xfd,
	0x60, 0xb7, 0xda, 0xef, 0xe7, 0xd7, 0x5e, 0xc4, 0xd4, 0x5e, 0xc9, 0x01, 0x3f, 0x8b, 0xb0, 0x9f,
	0x41, 0x75, 0x46, 0xce, 0xa8, 0x7a, 0xbe, 0x5b, 0xed, 0x56, 0x4e, 0x44, 0xc6, 0xc3, 0x5e, 0xc9,
	0x51, 0xd3, 0xf2, 0xd4, 0xd2, 0x93, 0xd7, 0x41, 0x8c, 0xab, 0x37, 0x5c, 0x3c, 0x35, 0x73, 0xf4,
	0xc7, 0x9a, 0xe0, 0xa4, 0x77, 0xc5, 0x8c, 0xd1, 0x01, 0x00, 0x79, 0x2d, 0x12, 0xac, 0x43, 0x62,
	0x4d, 0x1d, 0xba, 0x9d, 0x3f, 0x74, 0x73, 0xa2, 0xfb, 0x47, 0x92, 0x25, 0x63, 0xe4, 0x51, 0x24,
	0x92, 0xb9, 0x53, 0x27, 0xe9, 0x58, 0x9a, 0x31, 0xbd, 0xe0, 0xcc, 0x3b, 0x27, 0x22, 0xf5, 0x53,
	0x7d, 0xc5, 0x8c, 0xde, 0xe9, 0x48, 0x31, 0xd2, 0xcb, 0x93, 0x4a, 0xe8, 0xf1, 0xde, 0x63, 0x68,
	0x16, 0x17, 0x40, 0x16, 0xac, 0x9d, 0x93, 0xb9, 0x09, 0xf5, 0xf2, 0x13, 0xdd, 0x80, 0xf5, 0x0b,
	0x1c, 0xcc, 0x88, 0x89, 0xed, 0x7a, 0xf0, 0xa8, 0xf2, 0xa0, 0xdc, 0xd9, 0x06, 0x90, 0x7e, 0x33,
	0x17, 0xb1, 0x0d, 0xcd, 0xe2, 0xa6, 0xd1, 0x1d, 0xd8, 0xf6, 0xe2, 0x99, 0x3b, 0x49, 0xd8, 0x2c,
	0x76, 0xa9, 0x6f, 0xe2, 0x38, 0x78, 0xf1, 0xec, 0xa9, 0x84, 0xfa, 0xbe, 0xfd, 0x87, 0x32, 0x6c,
	0xe7, 0x8f, 0x12, 0xfd, 0x02, 0xd6, 0x63, 0x96, 0x08, 0x6e, 0x5e, 0xe1, 0x47, 0xd7, 0x1c, 0xf9,
	0xbe, 0xd9, 0x8f, 0x26, 0xef, 0xfd, 0x0a, 0x36, 0x8c, 0x3c, 0x82, 0xaa, 0x84, 0x4c, 0xe4, 0x52,
	0xdf, 0x32, 0x45, 0x19, 0x37, 0xe5, 0x53, 0x94, 0x86, 0x64, 0x8a, 0xb2, 0x7f, 0x02, 0xcd, 0xa2,
	0x9f, 0x94, 0x9a, 0x2c, 0xe3, 0xa9, 0x6f, 0xfb, 0x05, 0xb4, 0x0e, 0x13, 0x82, 0x05, 0x39, 0x1d,
	0x38, 0xe4, 0x87, 0x19, 0xe1, 0x02, 0x7d, 0x09, 0x1b, 0x85, 0x77, 0xb6, 0x73, 0xc5, 0x09, 0x3a,
	0x86, 0x82, 0xde, 0x87, 0x8d, 0x80, 0x4d, 0xa4, 0x1f, 0x8c, 0x23, 0x03, 0x36, 0xe9, 0xfb, 0xf6,
	0xbf, 0xca, 0xb0, 0xa5, 0xdf, 0xe4, 0x48, 0x60, 0xc1, 0x65, 0x42, 0xb9, 0x64, 0xc9, 0x39, 0x8d,
	0x26, 0x2e, 0x27, 0xc2, 0x1d, 0xcf, 0x05, 0xe1, 0xc6, 0x73, 0x2d, 0x33, 0x31, 0x22, 0xa2, 0x23,
	0x61, 0x95, 0x08, 0x2f, 0x30, 0x0d, 0xf0, 0x38, 0x20, 0xae, 0x7e, 0xca, 0x4a, 0x79, 0xd5, 0x69,
	0x2d, 0x70, 0xad, 0x5b, 0x46, 0xe2, 0x84, 0x48, 0xdb, 0x88, 0x9f, 0x32, 0xd7, 0x74, 0xe2, 0x49,
	0xe1, 0x8c, 0x88, 0x39, 0xa7, 0x93, 0x28, 0x23, 0x56, 0x35, 0x31, 0x85, 0x35, 0xd1, 0x7e, 0x04,
	0xcd, 0x45, 0x28, 0xd0, 0xa6, 0x7f, 0x0e, 0x96, 0x60, 0x02, 0x07, 0x6e, 0x32, 0x8b, 0x04, 0x0d,
	0x89, 0x1b, 0xa5, 0x96, 0x37, 0x15, 0xee, 0x68, 0xf8, 0x39, 0xb7, 0xff, 0x54, 0x86, 0x9d, 0x61,
	0xc2, 0x62, 0x92, 0x08, 0x4a, 0x78, 0xe6, 0xd0, 0x43, 0x58, 0x17, 0xf3, 0x98, 0xe8, 0x78, 0xdf,
	0x6c, 0x7f, 0x55, 0x0c, 0x3b, 0xcb, 0xf4, 0x1c, 0x76, 0x32, 0x8f, 0x89, 0xa3, 0x65, 0xed, 0x2f,
	0x95, 0x61, 0xb9, 0x09, 0x04, 0xb0, 0xa1, 0x8d, 0xb6, 0x4a, 0xa8, 0x01, 0xf5, 0x85, 0xd9, 0x56,
	0xd9, 0xfe, 0x7b, 0x19, 0x6e, 0x14, 0x55, 0xf3, 0x98, 0x45, 0x9c, 0xa0, 0x87, 0x60, 0x82, 0xa3,
	0xcb, 0xe5, 0xe6, 0xcc, 0x09, 0xdf, 0x5c, 0x89, 0xa4, 0x6a, 0xeb, 0xce, 0x56, 0x98, 0x3b, 0xc2,
	0x4e, 0x3e, 0xeb, 0x69, 0xe9, 0xca, 0xca, 0xcb, 0x2c, 0xfa, 0x2e, 0x97, 0x10, 0xd5, 0xd8, 0xfe,
	0x73, 0x15, 0x6e, 0x1e, 0xe2, 0x18, 0x8f, 0x69, 0x40, 0x97, 0x2c, 0xf3, 0x61, 0x87, 0xcf, 0x62,
	0x79, 0xb5, 0x89, 0xef, 0x26, 0x84, 0xb3, 0x59, 0xe2, 0x91, 0x34, 0x45, 0xde, 0xcf, 0x2d, 0x71,
	0xb5, 0xfc, 0xfe, 0x28, 0x15, 0x76, 0x8c, 0xac, 0x83, 0xf8, 0x32, 0xc4, 0xd1, 0xef, 0x21, 0x43,
	0xdd, 0x89, 0x74, 0xb7, 0xcb, 0x74, 0x4a, 0x6d, 0xb6, 0xdb, 0x6f, 0xb1, 0xc8, 0x53, 0x29, 0x7a,
	0x3c, 0x72, 0x2c, 0x5e, 0x44, 0xf8, 0xde, 0x3f, 0xca, 0xf0, 0xde, 0x8a, 0x2d, 0x32, 0x00, 0x1d,
	0xf8, 0x3a, 0x56, 0xd4, 0x1c, 0xf9, 0x89, 0x6e, 0xc2, 0x86, 0x43, 0x42, 0x76, 0x41, 0x4c, 0x91,
	0x67, 0x46, 0x12, 0x7f, 0x11, 0xfb, 0x58, 0x10, 0x53, 0xd2, 0x99, 0x11, 0x7a, 0x02, 0xb5, 0xd4,
	0x2b, 0xea, 0xea, 0x36, 0xdb, 0xf7, 0x7e, 0xdc, 0xde, 0x85, 0x2f, 0x16, 0xb2, 0xf6, 0xf7, 0x50,
	0x5b, 0x58, 0x55, 0x87, 0xf5, 0x53, 0x59, 0x30, 0x58, 0x25, 0x54, 0x83, 0xea, 0xc8, 0xe3, 0xd4,
	0x2a, 0xcb, 0xaf, 0xd3, 0xd8, 0xa3, 0x56, 0x45, 0x4e, 0x0f, 0x03, 0x1c, 0x3d, 0xb4, 0xd6, 0x14,
	0x73, 0xf0, 0x9c, 0x7a, 0x56, 0x35, 0x77, 0xed, 0xd6, 0x8b, 0xd7, 0x6e, 0xc3, 0xbe, 0x07, 0xd6,
	0xb2, 0x87, 0xd0, 0x16, 0x6c, 0x9a, 0x00, 0x6a, 0x95, 0xa4, 0x9a, 0x67, 0x34, 0x9a, 0xbd, 0xb6,
	0xca, 0xf6, 0x3f, 0xcb, 0x50, 0x4b, 0xab, 0x1d, 0xf4, 0x11, 0x80, 0xc7, 0x22, 0x91, 0xb0, 0x20,
	0x20, 0x89, 0x09, 0x73, 0x39, 0x44, 0xba, 0x2f, 0x98, 0x45, 0xa6, 0x1e, 0x93, 0x9f, 0xb2, 0x7c,
	0x9d, 0x32, 0x6e, 0x82, 0x9f, 0x2e, 0xbe, 0x6b, 0x12, 0x50, 0xd5, 0xf9, 0x5d, 0xa8, 0xca, 0x47,
	0x63, 0xfc, 0xb4, 0x53, 0xc8, 0x92, 0xfc, 0x5c, 0xbd, 0x2a, 0x45, 0x90, 0x5a, 0x12, 0x82, 0x7d,
	0x97, 0x45, 0xc1, 0x3c, 0x2d, 0x82, 0x25, 0x70, 0x1c, 0x05, 0x73, 0x3b, 0x82, 0xfa, 0xa2, 0xb2,
	0x2a, 0xae, 0x57, 0xbe, 0x66, 0xbd, 0xca, 0x5b, 0xad, 0xb7, 0xb6, 0xb4, 0xde, 0xdf, 0x2a, 0x50,
	0x5f, 0x14, 0x65, 0x32, 0xb0, 0xca, 0xf2, 0xcd, 0x24, 0x98, 0xba, 0xb3, 0x1e, 0x51, 0xaf, 0xef,
	0xcb, 0xb0, 0x1f, 0x62, 0xcf, 0xc5, 0xbe, 0x9f, 0x10, 0xce, 0xcd, 0xce, 0x21, 0xc4, 0xde, 0x81,
	0x46, 0x64, 0xb8, 0x0a, 0xc8, 0x04, 0x7b, 0x73, 0x97, 0x5f, 0x52, 0xe1, 0x4d, 0xa5, 0x86, 0xaa,
	0x62, 0x35, 0x35, 0x3e, 0x52, 0x70, 0xdf, 0x97, 0xcd, 0x81, 0x5c, 0x21, 0xc2, 0x21, 0x51, 0x7b,
	0xaf, 0x3b, 0x9b, 0x11, 0xf5, 0x9e, 0xe3, 0x90, 0xa0, 0x9f, 0x82, 0x21, 0xbb, 0xf2, 0x30, 0x17,
	0xd1, 0xbd, 0x57, 0x72, 0xb6, 0x35, 0x3e, 0x64, 0x89, 0xe8, 0xfb, 0xe8, 0x0b, 0x58, 0xf3, 0x29,
	0x33, 0xa5, 0x45, 0xb1, 0x1a, 0x61, 0x1d, 0xec, 0x9d, 0x93, 0xc8, 0xef, 0x95, 0x1c, 0xc9, 0x91,
	0x54, 0x81, 0x63, 0x53, 0x53, 0xe4, 0xa9, 0x27, 0x38, 0xce, 0x51, 0x05, 0x8e, 0x3b, 0x75, 0xd8,
	0x1c, 0x6b, 0xc4, 0xee, 0xc8, 0x66, 0x31, 0x55, 0x25, 0xdd, 0x97, 0x6d, 0xca, 0x1c, 0x02, 0x4f,
	0xb7, 0x73, 0x0b, 0x36, 0x0b, 0xc6, 0x3a, 0x1b, 0xb1, 0x32, 0xd2, 0xbe, 0x03, 0x90, 0xad, 0x21,
	0x93, 0xa0, 0xda, 0xb1, 0x49, 0x82, 0xf2, 0xdb, 0xbe, 0x0f, 0xd6, 0x72, 0x51, 0xab, 0xfb, 0x4e,
	0x2e, 0x70, 0xe4, 0x91, 0x6c, 0x35, 0x48, 0xa1, 0xbe, 0x6f, 0x7f, 0x0b, 0xcd, 0x62, 0x11, 0x2b,
	0x6f, 0xa9, 0xc0, 0x93, 0xb4, 0xca, 0x10, 0x58, 0x35, 0x7c, 0x09, 0x63, 0x85, 0x14, 0x5d, 0x93,
	0x80, 0x4a, 0xd0, 0x6d, 0xd8, 0x19, 0x30, 0x9f, 0x9e, 0xcd, 0xf5, 0x73, 0x4a, 0xb3, 0xc5, 0x9b,
	0x9a, 0x44, 0xfb, 0x00, 0x6e, 0x6a, 0x99, 0xc5, 0xb3, 0x4b, 0xc5, 0x0a, 0x4d, 0x09, 0x8d, 0x7c,
	0xf2, 0x7a, 0xa5, 0xd1, 0xe9, 0x4b, 0xd4, 0x4e, 0xe0, 0xc3, 0x25, 0x15, 0x26, 0xa5, 0x1b, 0x45,
	0x57, 0x35, 0x42, 0xe5, 0xff, 0xbb, 0x11, 0xaa, 0x5c, 0xd9, 0x08, 0xfd, 0xa5, 0x0a, 0xef, 0xeb,
	0x45, 0x17, 0x11, 0x69, 0xb1, 0x9a, 0x7e, 0x3a, 0x65, 0xf5, 0x74, 0xf2, 0xf7, 0x42, 0xf3, 0x73,
	0x8f, 0xe7, 0x00, 0xea, 0x0b, 0xb5, 0x26, 0xf5, 0x7c, 0xb2, 0xc2, 0x5f, 0xf6, 0x4b, 0xaf, 0xe4,
	0x64, 0x52, 0xe8, 0xe4, 0x8a, 0x5e, 0x40, 0x97, 0xf1, 0x77, 0xaf, 0xd7, 0x54, 0x70, 0x4f, 0xaf,
	0xb4, 0xda, 0x1a, 0x3c, 0x80, 0x8d, 0x5c, 0x4d, 0x51, 0xac, 0xef, 0xae, 0x38, 0xe1, 0x5e, 0xc9,
	0x31, 0x7c, 0xd4, 0x86, 0xfa, 0xa2, 0x1d, 0x34, 0x35, 0xfd, 0x55, 0xdd, 0x60, 0xaf, 0xe4, 0xd4,
	0xd2, 0x7e, 0x10, 0x7d, 0x03, 0x90, 0xb5, 0x83, 0xe6, 0xe9, 0x5d, 0xd9, 0x0d, 0xca, 0xad, 0x2f,
	0xfa, 0x41, 0x29, 0x96, 0x6b, 0x07, 0x37, 0x57, 0xc4, 0x16, 0x91, 0x47, 0x8a, 0x65, 0x0d, 0x61,
	0x77, 0xa5, 0x21, 0xac, 0x29, 0xd1, 0x37, 0x35, 0x84, 0xbd, 0xd2, 0x52, 0x4b, 0xd8, 0x81, 0x2c,
	0x79, 0xdd, 0xfb, 0x0a, 0x20, 0x3b, 0x5a, 0xb4, 0x09, 0x6b, 0x07, 0xdd, 0xae, 0x55, 0x92, 0x69,
	0xc5, 0x39, 0x1a, 0x1c, 0x9f, 0x1e, 0x59, 0x65, 0xf9, 0xfd, 0x62, 0xd8, 0x3d, 0x38, 0x39, 0xb2,
	0x2a, 0xf7, 0x5e, 0x41, 0x2d, 0x0d, 0xa2, 0xe8, 0x16, 0xec, 0x48, 0x97, 0xb8, 0xdd, 0xfe, 0xe8,
	0x3b, 0xf7, 0xe4, 0xd5, 0xf0, 0xc8, 0x3d, 0xed, 0x75, 0x7f, 0x6e, 0x95, 0xae, 0x9e, 0xf8, 0x9d,
	0x55, 0x46, 0xb7, 0xe1, 0xd6, 0xd2, 0xc4, 0xb0, 0xf7, 0x6a, 0xd4, 0x3f, 0x3c, 0x78, 0x66, 0x55,
	0xda, 0xff, 0xa9, 0x42, 0xe5, 0x74, 0x80, 0x7e, 0x0d, 0xb5, 0xb4, 0x04, 0x46, 0xf9, 0x96, 0x70,
	0xa9, 0x2e, 0xde, 0xbb, 0xb9, 0xaf, 0xff, 0x6b, 0xed, 0xa7, 0xff, 0xb5, 0xf6, 0x8f, 0xc2, 0x58,
	0xcc, 0xd1, 0x63, 0x80, 0x13, 0x82, 0x13, 0x9f, 0x5d, 0x46, 0xa7, 0x03, 0x74, 0x0d, 0xeb, 0x5a,
	0xe9, 0x87, 0xb0, 0x39, 0xc4, 0x33, 0x4e, 0xde, 0x41, 0xf4, 0x91, 0x4a, 0xe5, 0xb3, 0xf0, 0x5d,
	0x64, 0x1f, 0xc0, 0xc6, 0x4b, 0x4c, 0xc5, 0x3b, 0x48, 0x7e, 0x07, 0xcd, 0x62, 0xb5, 0x71, 0xad,
	0x86, 0x4f, 0x7e, 0xb4, 0x40, 0x41, 0xc7, 0xb0, 0x9d, 0xaf, 0x53, 0xd1, 0x47, 0x6f, 0xae, 0x8d,
	0xf7, 0x3e, 0xbe, 0x76, 0xde, 0x28, 0xfc, 0x0d, 0x34, 0x8b, 0x81, 0x06, 0xdd, 0x59, 0x79, 0x8d,
	0x4b, 0x31, 0xe8, 0xda, 0x9d, 0xfe, 0x12, 0xaa, 0xbf, 0x9d, 0x51, 0xf1, 0xb6, 0x1e, 0xea, 0x6c,
	0x7d, 0x9f, 0xfd, 0x29, 0x1d, 0x6f, 0xa8, 0xc9, 0xfb, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xf3,
	0x2a, 0x60, 0xa8, 0x4e, 0x15, 0x00, 0x00,
}
