---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica1
  labels:
    app: busybox
spec:
  selector:
     matchLabels:
      app: replica1
  replicas: 140
  template:
    metadata:
      labels:
        app: replica1
    spec:
#      runtimeClassName: kata-vm-isolation
      containers:
        - name: busy
          image: "mcr.microsoft.com/aks/e2e/library-busybox:master.220314.1-linux-amd64"
          command:
            - /bin/sh
          args:
            - "-c"
            - while true; do echo hello; sleep 10; done
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
