# Copyright (c) Microsoft Corporation.

name: Check policy samples

on:
  pull_request:

jobs:
  check-policy-samples:
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install yq
      env:
        INSTALL_IN_GOPATH: false
      run: |
        ./ci/install_yq.sh

    - name: Install Rust
      run: |
        ./tests/install_rust.sh
        echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

    - name: Install protobuf-compiler
      run: |
        sudo apt-get -y install protobuf-compiler

    - name: Install devicemapper
      run: | 
        sudo apt-get -y install libdevmapper-dev

    - name: Install libseccomp
      run: |
        libseccomp_install_dir=$(mktemp -d -t libseccomp.XXXXXXXXXX)
        gperf_install_dir=$(mktemp -d -t gperf.XXXXXXXXXX)
        ./ci/install_libseccomp.sh "${libseccomp_install_dir}" "${gperf_install_dir}"
        echo "Set environment variables for the libseccomp crate to link the libseccomp library statically"
        echo "LIBSECCOMP_LINK_TYPE=static" >> $GITHUB_ENV
        echo "LIBSECCOMP_LIB_PATH=${libseccomp_install_dir}/lib" >> $GITHUB_ENV

    - name: Configure containerd
      run: |
        sudo containerd config default | sudo dd of=/etc/containerd/config.toml
        sudo systemctl restart containerd
        sudo systemctl is-active containerd

    - name: Update policy samples
      working-directory: ./src/tools/genpolicy
      run: |
        python3 update_policy_samples.py

    - name: Show diff
      run: |
        git diff

    - name: Check policy samples
      run: |
        git diff-files --exit-code
